Repository Inist-CNRS/lodex, pull requests merged in 2019-10, with the labels that each got.

#944 Remove the div which breaks the front rendering
  src/api/controller/front.js
Labels: Ready For Review

#946 Bump version to v11.0.0
  package-lock.json
  package.json
Labels: Ready For Review

#947 Sort Search Results
  src/app/js/lib/components/SortButton.js
  src/app/js/public/facet/FacetValueList.js
  src/app/js/public/graph/GraphPage.js
  src/app/js/public/search/Facets.js
  src/app/js/public/search/Search.js
  src/app/js/public/search/SearchResultList.js
  src/app/js/public/search/SearchResultSort.js
  src/app/js/public/search/SearchResultSort.spec.js
  src/app/js/public/search/reducer.js
  src/app/js/public/search/sagas.js
Labels: Ready For Review, Trello

#950 Graph - Remove the global Graph page page and the table of resources on single Graph pages
  config.json
  src/api/e2e/ssr.spec.js
  src/app/js/fields/FieldDisplayInListInput.js
  src/app/js/fields/index.js
  src/app/js/fields/index.spec.js
  src/app/js/fields/ontology/EditOntologyFieldForm.js
  src/app/js/fields/selectors.js
  src/app/js/fields/wizard/StepDisplay.js
  src/app/js/public/Routes.js
  src/app/js/public/breadcrumb/Breadcrumb.spec.js
  src/app/js/public/graph/GraphPage.js
  src/app/js/public/graph/routes.js
  src/app/js/public/menu/MenuItem.js
  src/app/js/public/menu/MenuItem.spec.js
  src/app/js/public/menu/NavBar.js
Labels: Ready For Review, Trello

#952 Resources Navigation - Swipe left and right on mobile
  src/app/js/lib/components/NavButton.js
  src/app/js/lib/hooks/useSwiper.js
  src/app/js/public/Routes.js
  src/app/js/public/resource/ResourceNavigation.js
Labels: Ready For Review, Trello

#951 Breadcrumb - Load config using Redux Saga
  src/api/controller/api/breadcrumb.js
  src/api/controller/api/index.js
  src/api/controller/front.js
  src/app/js/public/breadcrumb/Breadcrumb.js
  src/app/js/public/breadcrumb/Breadcrumb.spec.js
  src/app/js/public/breadcrumb/BreadcrumbItem.js
  src/app/js/public/breadcrumb/loadBreadcrumbSaga.js
  src/app/js/public/breadcrumb/reducer.js
  src/app/js/public/menu/AdvancedPage.js
  src/app/js/public/menu/MenuItem.js
  src/app/js/public/menu/NavBar.js
  src/app/js/public/reducers.js
  src/app/js/public/sagas.js
  src/app/js/public/selectors.js
  src/app/js/user/index.js
Labels: Ready For Review, Trello

#958 Display again the admin entry in the menu
  src/app/js/public/menu/NavBar.js
Labels: Ready For Review, Trello

#960 Home Page - Hide graphs that are not supposed to appear
  src/app/js/characteristic/index.js
  src/app/js/characteristic/index.spec.js
Labels: Ready For Review, Trello

#962 Ressource - Allow to edit Root and Composite Fields values
  src/app/js/fields/editFieldValue/CompositeFieldInput.js
  src/app/js/fields/editFieldValue/CompositeFieldInput.spec.js
  src/app/js/fields/editFieldValue/EditButton.js
  src/app/js/fields/index.js
Labels: Ready For Review, Trello

#961 Perfs - Optimize Loading
  .gitignore
  Makefile
  README.md
  package-lock.json
  package.json
  src/api/controller/front.js
  src/app/webpack.config.babel.js
Labels: Ready For Review, Trello

#964 Refactoring - Fix SSR and Advanced Page
  src/app/js/public/menu/AdvancedPage.js
  src/app/webpack.config.babel.js
Labels: Ready For Review, Trello

#965 Bump version to v11.0.5 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#966 Fix the modal actions which are hidden by the menu
  src/app/js/admin/Appbar/ModelMenu.js
  src/app/js/fields/addField/AddField.js
  src/app/js/fields/wizard/index.js
  src/app/js/lib/components/ButtonWithDialog.js
  src/app/js/public/resource/HideResource.js
Labels: Ready For Review, Trello

#953 Fix e2e tests
  Makefile
  cypress/fixtures/model/concat.json
  cypress/fixtures/model/simple.json
  cypress/integration/book_summary.spec.js
  cypress/integration/chart_menu.spec.js
  cypress/integration/formats.spec.js
  cypress/integration/graph_page.spec.js
  cypress/integration/hiding_value.spec.js
  cypress/integration/login.spec.js
  cypress/integration/model.spec.js
  cypress/integration/publication.spec.js
  cypress/integration/search.spec.js
  cypress/support/datasetImportPage.js
  cypress/support/forms.js
  cypress/support/graphPage.js
  cypress/support/homePage.js
  cypress/support/modelPage.js
  cypress/support/searchDrawer.js
  package-lock.json
  package.json
  src/app/js/public/Drawer.js
  src/app/js/public/Property/index.js
  src/app/js/public/Stats.js
  src/app/js/public/menu/AdvancedPage.js
  src/app/js/public/resource/Detail.js
  src/app/js/public/resource/RemovedDetail.js
Labels: Ready For Review, Trello

#967 Bump version to v11.0.6 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#969 Breadcrumb - Improve the visibility
  src/app/js/public/breadcrumb/Breadcrumb.js
Labels: Ready For Review, Trello

#972 Login - Fix infinite loop of "login?page=%2F" in url
  src/app/js/lib/sagas/fetchSaga.js
Labels: Ready For Review, Trello

#968 Fix add resource
  Makefile
  cypress/fixtures/model/simple.json
  cypress/integration/book_summary.spec.js
  cypress/integration/hiding_value.spec.js
  cypress/integration/publication.spec.js
  cypress/integration/resource.spec.js
  cypress/support/bookSummary.js
  cypress/support/datasetImportPage.js
  cypress/support/dialog.js
  cypress/support/resourcePage.js
  cypress/support/searchDrawer.js
  src/app/js/fields/addField/AddFieldForm.js
  src/app/js/fields/editFieldValue/FieldInput.js
  src/app/js/formats/DefaultFormat/index.js
  src/app/js/formats/identifier-badge/index.js
  src/app/js/formats/list/index.js
  src/app/js/formats/markdown/index.js
  src/app/js/formats/uri/index.js
  src/app/js/lib/components/ButtonWithDialog.js
  src/app/js/public/Property/index.js
  src/app/js/public/resource/CreateResourceForm.js
  src/app/js/public/search/SearchResult.js
  src/app/translations.tsv
  src/common/fields/isFieldRequired.js
  src/common/fields/isFieldRequired.spec.js
  src/common/lib/isEmpty.js
  src/common/lib/isEmpty.spec.js
Labels: Ready For Review, Trello

#973 Search - Results take the whole space available when there is no facets
  src/app/js/public/search/Search.js
  src/app/js/public/search/SearchResult.js
Labels: Ready For Review, Trello

#974 Resource - Allow https in uri when adding a new resource
  src/app/js/public/resource/CreateResourceForm.js
  src/app/js/public/search/SearchResult.js
  src/app/translations.tsv
  src/common/uris.js
Labels: Ready For Review, Trello

#975 Bump version to v11.0.7 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#970 Copy Facets
  src/app/js/public/Routes.js
  src/app/js/public/ScrollToTop.js
  src/app/js/public/breadcrumb/Breadcrumb.js
  src/app/js/public/facet/FacetValueList.spec.js
  src/app/js/public/facet/index.js
  src/app/js/public/facet/selectors.js
  src/app/js/public/graph/GraphPage.js
  src/app/js/public/menu/MenuItem.js
  src/app/js/public/menu/NavBar.js
  src/app/js/public/search/Search.js
  src/app/js/public/search/sagas.js
  src/app/translations.tsv
Labels: Work In Progress

#978 Resource - Allow the redirect field to be empty
  package-lock.json
  package.json
  src/app/js/formats/redirect/index.js
Labels: Ready For Review, Trello

#977 Graphs - Remove export as png in all graphs
  src/app/js/formats/bubbleChart/BubbleView.js
  src/app/js/formats/cartography/CartographyView.js
  src/app/js/formats/distributionChart/global-bar-chart/BarChartView.js
  src/app/js/formats/distributionChart/global-pie-chart/PieChartView.js
  src/app/js/formats/distributionChart/global-radar-chart/RadarChartView.js
  src/app/js/formats/exportableToPng.js
  src/app/js/formats/heatmap/HeatMapView.js
  src/app/js/formats/hierarchy/Hierarchy.js
  src/app/js/formats/network/NetworkView.js
  src/app/js/formats/streamgraph/Streamgraph.js
  src/app/js/lib/convertHtmlToPng.js
Labels: Ready For Review, Trello

#979 Test copy facets
  cypress/integration/graph_page.spec.js
  cypress/support/graphPage.js
  cypress/support/searchDrawer.js
  src/app/js/public/search/Search.js
Labels: Ready For Review, Trello

#980 Resource Navigation - Rename copy facets css class
  cypress/support/datasetImportPage.js
  cypress/support/graphPage.js
  src/app/js/public/graph/GraphPage.js
Labels: Ready For Review, Trello

#983 Bump version to v11.1.0 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#981 Similar Resource - Register new routine close-by
  config.json
  package-lock.json
  package.json
Labels: Ready For Review, Trello

#985 Bump version to v11.1.1111 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#982 Ressource - Improve the edition of the Root Field value
  src/api/controller/api/characteristic.js
  src/api/controller/api/characteristic.spec.js
  src/app/js/characteristic/DatasetCharacteristicItem.js
  src/app/js/characteristic/DatasetCharacteristicItem.spec.js
  src/app/js/characteristic/DatasetCharacteristics.js
  src/app/js/fields/editFieldValue/CompositeFieldInput.js
  src/app/js/fields/editFieldValue/CompositeFieldInput.spec.js
  src/app/js/fields/shouldDisplayField.js
  src/app/js/fields/shouldDisplayField.spec.js
  src/app/js/public/Property/index.js
  src/app/js/public/Property/index.spec.js
  src/app/js/public/resource/Detail.js
  src/app/js/public/resource/Detail.spec.js
  src/app/js/public/search/SearchResult.js
  src/app/js/public/search/SearchResultList.js
  src/app/js/public/search/SearchResultSort.js
  src/app/translations.tsv
Labels: Ready For Review, Trello

#988 Bump version to v11.1.2 🚀
  package-lock.json
  package.json
Labels: Ready For Review
