Repository Inist-CNRS/lodex, pull requests merged in 2019-12, with the labels that each got.

#1010 Resource Navigation - Display a full screen message when redirecting
  src/api/controller/front.js
  src/app/admin.html
  src/app/custom/index.html
  src/app/index.html
  src/app/js/formats/redirect/RedirectView.js
  src/app/js/formats/redirect/RedirectView.spec.js
  src/app/translations.tsv
Labels: Ready For Review, Trello

#1011 Search / Graph - Use orange in Search and Graph Filter Clear buttons
  src/app/js/public/dataset/Filter.js
  src/app/js/public/search/Search.js
Labels: Ready For Review, Trello

#1012 Similar Resources - Remove unused URI param in the Aster Plot Admin Panel
  src/app/js/formats/asterPlotChart/AsterPlotChartAdmin.js
Labels: Ready For Review, Trello

#1013 Bump version to v11.6.0 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#1014 Display a spinner when loading the graph
  src/app/js/formats/injectData.js
  src/app/js/formats/resources-grid/ResourcesGridView.js
  src/app/js/formats/sparql/SparqlRequest.js
Labels: Trello

#1015 Graph - Fix bubulles which is not refreshed when using facets
  package-lock.json
  package.json
  src/app/js/formats/bubbleChart/BubbleView.js
Labels: Ready For Review, Trello

#1018 Load only visible formats thanks to the Intersection Observer API
  cypress/support/homePage.js
  package-lock.json
  package.json
  src/app/js/characteristic/DatasetCharacteristicItem.js
  src/app/js/characteristic/DatasetCharacteristicItem.spec.js
  src/app/js/lib/components/Loading.js
Labels: Ready For Review, Trello

#1017 now the url points to a tag (it's more safely)
  config.json
Labels: Ready For Review

#1019 Change the icon of the export button
  src/app/js/public/ExportButton.js
Labels: Ready For Review, Trello

#1020 Graph - Facets are not cropped anymore
  src/app/js/public/facet/FacetValueList.js
  src/app/js/public/graph/GraphPage.js
Labels: Ready For Review, Trello

#1021 Bump version to v11.6.1 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#1022 Upgrade dependencies
  package-lock.json
  package.json
Labels: Ready For Review

#1023 Graph - Fix Sort Button style
  src/app/js/lib/components/SortButton.js
Labels: Ready For Review, Trello

#1024 Fix loading styles and increase loading box height
  src/app/js/characteristic/DatasetCharacteristicItem.js
Labels: Ready For Review, Trello

#1025 Bump version to v11.6.2 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#1016 Dynamic translations
  src/api/controller/api/index.js
  src/api/controller/api/translate.js
  src/api/controller/front.js
  src/api/services/translations.js
  src/app/custom/translations.tsv
  src/app/js/admin/index.js
  src/app/js/configureStore.js
  src/app/js/embeddedIstexSummary/index.js
  src/app/js/i18n/sagas/initializeLanguage.js
  src/app/js/i18n/sagas/setLanguage.js
  src/app/js/i18n/translations/en.js
  src/app/js/i18n/translations/fr.js
  src/app/js/i18n/translations/index.js
  src/app/js/public/index.js
  src/app/translations.js
  src/app/webpack.config.babel.js
  src/common/getLocale.js
Labels: Ready For Review, Trello

#1026 Use same dataset display
  cypress/integration/search.spec.js
  cypress/support/searchDrawer.js
  src/app/custom/translations.tsv
  src/app/js/public/Stats.js
  src/app/js/public/dataset/DatasetStats.js
  src/app/js/public/graph/GraphPage.js
  src/app/js/public/search/Search.js
  src/app/js/public/search/SearchStats.js
  src/app/js/public/search/reducer.js
  src/app/js/public/search/sagas.js
Labels: Ready For Review, Trello

#1027 Change the layout of the export button
  cypress/integration/search.spec.js
  src/app/custom/translations.tsv
  src/app/js/characteristic/DatasetCharacteristicItem.js
  src/app/js/public/ExportButton.js
  src/app/js/public/export/ExportMenuItem.js
  src/app/js/public/resource/Detail.js
  src/app/js/public/search/Search.js
Labels: Ready For Review, Trello

#1028 Bump version to v11.7.0 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#1029 Graph - Fix floating-point addition issue in the Steamgraph format
  src/app/js/formats/streamgraph/Streamgraph.js
  src/app/js/formats/streamgraph/utils.js
Labels: Ready For Review, Trello

#1030 Graph - Fix padding in mouse tooltips
  src/app/js/formats/shared/MouseIcon.js
Labels: Ready For Review, Trello

#1032 Impossible to have a null value in transformer args
  src/app/js/public/Property/index.js
  src/common/lib/isUndefinedOrEmpty.js
  src/common/lib/isUndefinedOrEmpty.spec.js
  src/common/transformers/VALUE.js
  src/common/transformers/VALUE.spec.js
  src/common/validateFields.js
  src/common/validateFields.spec.js
Labels: Ready For Review, Trello

#1033 Fix duplication of uri when the value of a format already contains one
  src/app/js/formats/asterPlotChart/AsterPlotChartView.js
  src/app/js/formats/injectData.js
  src/app/js/formats/lodex-field/LodexFieldView.js
  src/app/js/formats/sagas.js
  src/app/js/formats/sagas.spec.js
Labels: Ready For Review, Trello

#1034 Load graph with filters
  src/app/js/formats/sagas.js
  src/app/js/formats/sagas.spec.js
Labels: Ready For Review, Trello

#1036 Bump version to v11.7.1 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#1037 Remove padding left on refresh button
  src/app/js/formats/shared/CenterIcon.js
Labels: Ready For Review, Trello

#1038 Graph - Do not show trailing zeros in Streamgraph
  src/app/js/formats/streamgraph/Streamgraph.js
  src/app/js/formats/streamgraph/utils.js
Labels: Ready For Review, Trello

#1039 Load facets when the value is not a URL
  src/app/js/formats/sagas.js
Labels: Ready For Review, Trello

#1042 Use filter only on field with dataset cover
  src/app/js/formats/sagas.js
Labels: Ready For Review, Trello

#1040 Similar Resources - Create a `distance-with` routine
  config.json
  package-lock.json
  package.json
  src/api/controller/api/run.js
Labels: Ready For Review, Trello

#1041 AsterPlot - Choose color set
  src/app/custom/translations.tsv
  src/app/js/formats/asterPlotChart/AsterPlot.js
  src/app/js/formats/asterPlotChart/AsterPlotChartAdmin.js
  src/app/js/formats/asterPlotChart/AsterPlotChartView.js
  src/app/js/formats/bubbleChart/BubbleAdmin.js
  src/app/js/formats/bubbleChart/BubbleView.js
  src/app/js/formats/colorUtils.js
  src/app/js/formats/distributionChart/global-bar-chart/BarChartAdmin.js
  src/app/js/formats/distributionChart/global-pie-chart/PieChartAdmin.js
  src/app/js/formats/distributionChart/global-radar-chart/RadarChartAdmin.js
  src/app/js/formats/emphased-number/Bigbold.js
  src/app/js/formats/emphased-number/EmphasedNumberAdmin.js
  src/app/js/formats/hierarchy/Hierarchy.js
  src/app/js/formats/hierarchy/HierarchyAdmin.js
  src/app/js/formats/identifier-badge/IdentifierBadgeAdmin.js
  src/app/js/formats/network/NetworkAdmin.js
  src/app/js/formats/streamgraph/Streamgraph.js
  src/app/js/formats/streamgraph/StreamgraphAdmin.js
  src/app/js/formats/title/TitleAdmin.js
Labels: Ready For Review, Trello

#1043 Bump version to v11.7.2 🚀
  package-lock.json
  package.json
Labels: Ready For Review

#1044 Dynamic exporters, routines and loaders
  src/api/controller/api/export.js
  src/api/controller/api/loader.js
  src/api/controller/api/run.js
  src/api/controller/api/upload.js
  src/api/exporters/README.md
  src/api/loaders/README.md
  src/api/routines/README.md
  src/api/services/script.js
  src/app/custom/exporters/README.md
  src/app/custom/loaders/README.md
  src/app/custom/routines/README.md
Labels: Ready For Review, Trello
