Repository Inist-CNRS/lodex, pull requests merged in 2019-09, with the labels that each got.

#932 Move the menu to the bottom of the page
  docker-compose.yml
  src/app/js/public/Drawer.js
  src/app/js/public/Routes.js
  src/app/js/public/menu/MenuItem.js
  src/app/js/public/menu/NavBar.js
  src/app/js/public/resource/CreateResource.js
Labels: Ready For Review

#934 Upgrade dependencies
  .eslintrc
  Makefile
  package-lock.json
  package.json
  src/app/js/admin/ActionButton.js
  src/app/js/admin/Appbar/ImportFieldsDialog.js
  src/app/js/admin/preview/publication/PublicationPreview.js
  src/app/js/admin/removedResources/RemovedResourceList.js
  src/app/js/admin/withInitialData.js
  src/app/js/fields/wizard/index.js
  src/app/js/lib/components/Link.js
  src/app/js/lib/components/Pagination.js
  src/app/js/lib/components/Tooltip.js
  src/app/js/lib/fetchPaginatedDataForComponent.js
  src/app/js/public/ExportShareMenuItem.js
  src/app/js/public/WidgetExportItem.js
  src/app/js/public/Widgets.js
  src/app/js/public/export/ExportSection.js
  src/app/js/public/menu/MenuItem.js
  src/app/js/public/menu/MenuItem.spec.js
Labels: Ready For Review

#935 Run tests in parallel
  .travis.yml
  Makefile
Labels: Ready For Review

#931 Use new @ezs packages
  package-lock.json
  package.json
  src/api/controller/api/export.js
  src/api/controller/api/run.js
  src/api/controller/api/upload.js
  src/api/services/script.js
  src/api/statements/README.md
  src/api/statements/testAll.js
  src/api/statements/testOne.js
Labels: Ready For Review

#933 Display Search and Graphs from the bottom of the screen
  docker-compose.yml
  src/app/js/public/Drawer.js
  src/app/js/public/graph/GraphSummary.js
  src/app/js/public/menu/NavBar.js
Labels: Ready For Review, Trello

#936 Use left, right menus
  config.json
  src/api/controller/api/menu.js
  src/api/controller/front.js
  src/app/js/public/menu/AdvancedPage.js
  src/app/js/public/menu/MenuItem.js
  src/app/js/public/menu/NavBar.js
  src/app/js/public/menu/NavBar.spec.js
  src/app/js/public/menu/reducer.js
Labels: Ready For Review

#937 Fix Search and Graph pages sliding from the bottom of the screen
  config.json
  package-lock.json
  package.json
  src/api/controller/api/menu.js
  src/api/controller/front.js
  src/app/js/admin/parsing/ParsingExcerpt.js
  src/app/js/lib/selectors.js
  src/app/js/public/Drawer.js
  src/app/js/public/graph/GraphSummary.js
  src/app/js/public/menu/AdvancedPage.js
  src/app/js/public/menu/MenuItem.js
  src/app/js/public/menu/NavBar.js
  src/app/js/public/menu/NavBar.spec.js
  src/app/js/public/menu/reducer.js
  src/app/js/public/search/Search.js
Labels: Ready For Review, Trello

#938 Display Facets in Search Page
  cypress/support/searchDrawer.js
  src/app/js/public/Drawer.js
  src/app/js/public/menu/NavBar.js
  src/app/js/public/search/AdvancedSearch.js
  src/app/js/public/search/Facets.js
  src/app/js/public/search/Search.js
  src/app/translations.tsv
Labels: Trello, Work In Progress

#939 Due to menu, increase bottom padding page size
  src/app/js/public/App.js
  src/app/js/public/App.spec.js
Labels: Ready For Review

#941 Put facets on the left side of the page
  src/app/js/public/graph/GraphPage.js
  src/app/js/public/search/Search.js
Labels: Ready For Review

#942 allow routine to use uri as a filter
  src/api/controller/api/run.js
Labels: Ready For Review

#943 Add breadcrumbs
  config.json
  package-lock.json
  src/api/controller/api/breadcrumb.js
  src/app/js/public/App.js
  src/app/js/public/Routes.js
  src/app/js/public/breadcrumb/Breadcrumb.js
  src/app/js/public/breadcrumb/Breadcrumb.spec.js
  src/app/js/public/breadcrumb/BreadcrumbItem.js
  src/app/js/public/menu/AdvancedPage.js
Labels: Ready For Review
