Repository Inist-CNRS/lodex, pull requests merged in 2020-10, with the labels that each got.

#1109 Fix data import by URL link
  src/api/controller/api/upload.js
Labels: Ready For Review, bug

#1108 Supprimer Moderation
  src/app/custom/translations.tsv
  src/app/js/admin/Appbar/index.js
  src/app/js/admin/Routes.js
  src/app/js/admin/contributedResources/ContributedResourceList.js
  src/app/js/admin/contributedResources/ContributedResourcePage.js
  src/app/js/admin/contributedResources/index.js
  src/app/js/admin/contributedResources/index.spec.js
  src/app/js/admin/contributedResources/sagas.js
  src/app/js/admin/contributedResources/sagas.spec.js
  src/app/js/admin/reducers.js
  src/app/js/admin/sagas.js
  src/app/js/admin/selectors.js
  src/app/js/user/index.js
Labels: Ready For Review

#1107 Add dev password to the Readme
  README.md
Labels: Ready For Review, enhancement

#1110 Correctif Import Ancien Modele
  cypress/fixtures/model/concat-obsolete.json
  cypress/integration/publication.spec.js
  cypress/support/datasetImportPage.js
  src/app/js/fields/TransformerList.js
  src/app/js/fields/wizard/StepTransforms.js
  src/common/transformers/index.js
Labels: Ready For Review, bug

#1112 add kbart key and correct spelling errors
  src/app/custom/translations.tsv
Labels: Ready For Review

#1114 Keep navigation links (previous and next resource)
  src/app/js/characteristic/DatasetCharacteristicItem.js
  src/app/js/configureStore.js
  src/app/js/lib/components/ButtonWithDialog.js
  src/app/js/lib/components/ButtonWithDialogForm.js
  src/app/js/public/resource/Resource.js
  src/app/js/public/resource/index.js
  src/app/js/public/search/Search.js
Labels: Ready For Review, bug

#1116 Bump to v11.16.3
  package-lock.json
  package.json
Labels: Ready For Review

#1069 Node 12
  Dockerfile
  Dockerfile.spec
  docker-compose.dev.yml
  docker-compose.spec.yml
  package-lock.json
  package.json
  src/app/js/public/CustomPage.spec.js
Labels: Ready For Review

#1118 Update Travis NodeJS
  .travis.yml
Labels: Ready For Review

#1119 upgrade lodex-extended version and ezs/* dependencies
  config.json
  cypress/support/adminPage.js
  cypress/support/datasetImportPage.js
  package-lock.json
  package.json
  src/app/custom/translations.tsv
Labels: Ready For Review
