Repository Inist-CNRS/lodex, pull requests merged in 2023-10, with the labels that each got.

#1718 check the first object before generate tar file
  workers/exporters/bundle.ini
Labels: Ready For Review

#1704 Add an advanced mode to vega / vega lite chart
  cypress/integration/graph_page.spec.js
  cypress/integration/model.spec.js
  src/app/custom/translations.tsv
  src/app/js/formats/chartsUtils.js
  src/app/js/formats/shared/VegaAdvancedMode.js
  src/app/js/formats/vega-lite/component/bar-chart/BarChartAdmin.js
  src/app/js/formats/vega-lite/component/bar-chart/BarChartView.js
  src/app/js/formats/vega-lite/component/bubble-plot/BubblePlotAdmin.js
  src/app/js/formats/vega-lite/component/bubble-plot/BubblePlotView.js
  src/app/js/formats/vega-lite/component/cartography/CartographyAdmin.js
  src/app/js/formats/vega-lite/component/cartography/CartographyView.js
  src/app/js/formats/vega-lite/component/heatmap/HeatMapAdmin.js
  src/app/js/formats/vega-lite/component/heatmap/HeatMapView.js
  src/app/js/formats/vega-lite/component/pie-chart/PieChartAdmin.js
  src/app/js/formats/vega-lite/component/pie-chart/PieChartView.js
  src/app/js/formats/vega-lite/component/vega-lite-component/VegaLiteComponent.js
  src/app/js/formats/vega-lite/models/BarChart.js
  src/app/js/formats/vega-lite/models/BasicChart.js
  src/app/js/formats/vega-lite/models/BubblePlot.js
  src/app/js/formats/vega-lite/models/Cartography.js
  src/app/js/formats/vega-lite/models/HeatMap.js
  src/app/js/formats/vega-lite/models/PieChart.js
  src/app/js/formats/vega/component/flow-map/FlowMapAdmin.js
  src/app/js/formats/vega/component/flow-map/FlowMapView.js
  src/app/js/formats/vega/component/radar-chart/RadarChartAdmin.js
  src/app/js/formats/vega/component/radar-chart/RadarChartView.js
  src/app/js/formats/vega/models/BasicChartVG.js
  src/app/js/formats/vega/models/FlowMap.js
  src/app/js/formats/vega/models/RadarChart.js
Labels: Trello, Ready For Review

#1726 Fix workerqueues
  src/api/index.js
  src/api/services/mongoClient.js
  src/api/workers/index.js
  src/common/tests/fixtures.js
Labels: Ready For Review

#1729 Feat: remove obsolete instances links
  src/app/js/admin/Appbar/Menu.js
Labels: Ready For Review

#1727 Add loader for ISTEX tar.gz files
  config.json
  src/app/custom/translations.tsv
  workers/loaders/tar-gz.ini
Labels: Ready For Review

#1725 Add ace editor on vega-lite text field
  src/app/js/formats/shared/VegaAdvancedMode.js
  src/app/js/formats/vega-lite/VegaLiteAdmin.js
  src/app/js/lib/components/FormSourceCodeField.js
Labels: Ready For Review

#1728 Cypress Migration
  cypress.config.js
  cypress.json
  cypress/e2e/book_summary.cy.js
  cypress/e2e/chart_menu.cy.js
  cypress/e2e/enrichment.cy.js
  cypress/e2e/formats.cy.js
  cypress/e2e/graph_page.cy.js
  cypress/e2e/hiding_value.cy.js
  cypress/e2e/home_page.cy.js
  cypress/e2e/login.cy.js
  cypress/e2e/model.cy.js
  cypress/e2e/publication.cy.js
  cypress/e2e/search.cy.js
  cypress/e2e/subresource.cy.js
  cypress/support/adminNavigation.js
  cypress/support/enrichmentFormPage.js
  cypress/support/menu.js
  package-lock.json
  package.json
Labels: Ready For Review

#1708 Update github ci
  .github/workflows/lodex-ci.yml
  Makefile
  cypress/integration/phase_1/home_page.spec.js
  cypress/integration/phase_1/publication.spec.js
  cypress/integration/phase_1/subresource.spec.js
  cypress/integration/phase_2/book_summary.spec.js
  cypress/integration/phase_2/chart_menu.spec.js
  cypress/integration/phase_2/enrichment.spec.js
  cypress/integration/phase_2/formats.spec.js
  cypress/integration/phase_3/hiding_value.spec.js
  cypress/integration/phase_3/login.spec.js
  cypress/integration/phase_3/search.spec.js
  cypress/integration/phase_4/graph_page.spec.js
  cypress/integration/phase_4/model.spec.js
  docker-compose.spec.yml
  package.json
Labels: Ready For Review

#1715 Update to node 16
  .github/workflows/lodex-ci.yml
  .gitignore
  Dockerfile
  Dockerfile.spec
  Makefile
  docker-compose.dev.yml
  docker-compose.spec.yml
  docker-compose.yml
  globalConfig.json
  jest-mongodb-config.js
  package-lock.json
  package.json
  packages/ezsLodex/babel.config.js
  packages/transformers/babel.config.js
Labels: Ready To Merge

#1744 feat: process precomputed data
  .gitignore
  config.json
  src/api/controller/index.js
  src/api/controller/webhook.js
  src/api/models/enrichment.js
  src/api/models/precomputed.js
  src/api/services/enrichment/enrichment.js
  src/api/services/enrichment/enrichment.spec.js
  src/api/services/precomputed/precomputed.js
  src/api/workers/index.js
  src/api/workers/precomputer.js
  src/app/custom/translations.tsv
  src/app/js/admin/Appbar/JobProgress.js
  src/app/js/admin/precomputed/PrecomputedDataDialog.js
  src/app/js/admin/precomputed/PrecomputedForm.js
  src/app/js/admin/precomputed/PrecomputedList.js
  webservice_temp/.gitkeep
Labels: Work In Progress
