Repository Inist-CNRS/lodex, pull requests merged in 2023-11, with the labels that each got.

#1747 fix(precomputed): fix WS behaviour
  Dockerfile
  Dockerfile.spec
  config.json
  docker-compose.yml
  package-lock.json
  package.json
  src/api/controller/webhook.js
  src/api/services/precomputed/precomputed.js
  src/api/workers/precomputer.js
  src/app/custom/translations.tsv
  src/app/js/admin/Appbar/CancelProcessDialog.js
  src/app/js/admin/Appbar/JobProgress.js
  src/app/js/admin/api/job.js
Labels: Ready For Review

#1754 Add config to activate bull dashboard on start
  config.json
  src/api/index.js
Labels: Ready For Review

#1755 Feat(config): Add admin page for config
  configTenant.json
  src/api/controller/api/configTenant.js
  src/api/controller/api/index.js
  src/api/controller/api/login.spec.js
  src/api/controller/front.js
  src/api/controller/index.js
  src/api/controller/rootAdmin.js
  src/api/models/configTenant.js
  src/api/models/tenant.js
  src/app/custom/translations.tsv
  src/app/js/admin/Appbar/Menu.js
  src/app/js/admin/ConfigTenantRoute.js
  src/app/js/admin/Data.js
  src/app/js/admin/Sidebar/Sidebar.js
  src/app/js/admin/api/configTenant.js
  src/app/js/admin/configTenant/ConfigTenantForm.js
  src/app/js/admin/index.js
  src/app/js/root-admin/DeleteTenantDialog.js
  src/app/js/root-admin/Tenants.js
  src/app/js/user/index.js
Labels: Ready For Review

#1705 Add overlay to show loading when changing facet
  src/app/js/formats/injectData.js
  src/app/js/public/dataset/index.js
  src/app/js/public/dataset/index.spec.js
Labels: enhancement, Ready To Merge

#1740 Update webpack
  docker-compose.dev.yml
  docker-compose.spec.yml
  package-lock.json
  package.json
  src/app/webpack.config.babel.js
Labels: Ready For Review

#1751 Highly reduce the number of undelivered notifications
  src/app/js/formats/vega-lite/component/bar-chart/BarChartView.js
  src/app/js/formats/vega-lite/component/bubble-plot/BubblePlotView.js
  src/app/js/formats/vega-lite/component/cartography/CartographyView.js
  src/app/js/formats/vega-lite/component/heatmap/HeatMapView.js
  src/app/js/formats/vega-lite/component/pie-chart/PieChartView.js
Labels: bug, Ready For Review

#1758 fix: use run instead of open
  Makefile
Labels: bug, Ready For Review

#1759 Update Babel
  babel.config.js
  package-lock.json
  package.json
  packages/transformers/.babelrc
  src/app/js/formats/injectData.js
  workers/exporters/.jshintrc
Labels: Ready For Review

#1761 fix(precomputed): cleaning
  config.json
  src/api/services/precomputed/precomputed.js
Labels: Ready For Review

#1766 Set signout button in red color
  src/app/js/admin/Appbar/Menu.js
Labels: Ready For Review

#1767 Limit size of tenant name to 50
  src/app/js/root-admin/CreateTenantDialog.js
  src/app/js/root-admin/NameField.js
  src/common/tools/tenantTools.js
Labels: Ready For Review

#1769 Add ellipsys and title on bid descriptions in the tenant list
  src/app/js/root-admin/Tenants.js
Labels: Ready For Review

#1763 Update markdown-it
  package-lock.json
  package.json
Labels: Ready For Review

#1765 Fix(precompute): Fix issues from manual tests
  config.json
  src/api/index.js
  src/api/services/precomputed/precomputed.js
  src/app/custom/translations.tsv
Labels: Ready For Review

#1776 fix(tenant): tenant name can't exceed db limit
  src/api/controller/rootAdmin.js
  src/app/js/root-admin/CreateTenantDialog.js
  src/app/js/root-admin/NameField.js
  src/app/js/root-admin/Tenants.js
  src/common/tools/tenantTools.js
Labels: Ready For Review

#1775 Fix(various): Work on search optimisation.
  src/api/controller/api/enrichment.js
  src/api/controller/api/enrichment.spec.js
  src/api/controller/api/export.js
  src/api/controller/api/exportPDF.js
  src/api/models/publishedDataset.js
  src/api/models/publishedDataset.spec.js
  src/api/services/enrichment/enrichment.js
  src/app/js/lib/getQueryString.js
  src/app/js/public/ExportButton.js
  src/app/js/public/export/sagas/exportPublishedDataset.js
Labels: Ready For Review

#1777 Change some wording in tenants admin
  src/app/js/root-admin/CreateTenantDialog.js
  src/common/tools/tenantTools.js
Labels: Ready For Review

#1779 Fix columns of precomputed and label in jobprogress
  src/app/js/admin/Appbar/JobProgress.js
  src/app/js/admin/precomputed/PrecomputedList.js
Labels: Ready For Review

#1774 Add missing modules urls for ace editor
  package-lock.json
  package.json
  src/api/controller/front.js
  src/app/ace-webpack-loader.js
  src/app/admin.html
  src/app/js/admin/index.js
Labels: Ready For Review

#1781 fix(precomputed): Fix errors on precomputed
  src/api/controller/webhook.js
  src/api/services/repositoryMiddleware.js
  src/app/custom/translations.tsv
  src/app/js/admin/enrichment/EnrichmentForm.js
  src/app/js/admin/precomputed/PrecomputedForm.js
Labels: Ready For Review

#1784 Fix precompute when ws is failure
  src/api/controller/webhook.js
  src/api/services/precomputed/precomputed.js
Labels: Ready For Review

#1753 feat(precomputed): precomputed param in model
  packages/transformers/src/dollar-precomputed.js
  packages/transformers/src/dollar-precomputed.spec.js
  packages/transformers/src/dollar-webservice.js
  packages/transformers/src/index.js
  packages/transformers/src/operations/PRECOMPUTED.js
  packages/transformers/src/operations/PRECOMPUTED.spec.js
  packages/transformers/src/operations/WEBSERVICE.js
  packages/transformers/src/operations/WEBSERVICE.spec.js
  src/api/controller/api/parsing.js
  src/api/controller/api/parsing.spec.js
  src/app/custom/translations.tsv
  src/app/js/admin/parsing/index.js
  src/app/js/fields/sourceValue/SourceValueExternal.js
  src/app/js/fields/sourceValue/SourceValuePrecomputed.js
  src/app/js/fields/sourceValue/SourceValueToggle.js
Labels: Ready For Review

#1790 feat(precomputed): get data in publication
  packages/transformers/src/operations/PRECOMPUTED.js
  src/api/services/getDocumentTransformer.js
  src/api/services/publishCharacteristics.js
  src/api/services/publishCharacteristics.spec.js
  src/app/js/formats/checkPredicate.js
  src/app/js/formats/sagas.js
  src/app/js/lib/getDocumentTransformer.js
  src/common/getDocumentTransformer.js
Labels: Ready For Review

#1794 Fix covering placeholder in routine field
  src/app/js/fields/sourceValue/SourceValuePrecomputed.js
Labels: Ready For Review

#1796 Feat(precomputed): Display time since precomputed start
  src/api/models/precomputed.js
  src/api/services/precomputed/precomputed.js
  src/app/js/admin/precomputed/PrecomputedForm.js
  src/app/js/admin/precomputed/PrecomputedList.js
Labels: Ready For Review

#1795 Fix(precomputed): Cancel precomputed block on wehbhook retrieve
  src/api/controller/api/job.js
  src/api/controller/api/precomputed.js
  src/api/services/precomputed/precomputed.js
  src/api/workers/tools.js
  src/app/js/admin/Appbar/JobProgress.js
  src/app/js/admin/api/job.js
  src/app/js/user/index.js
Labels: Ready For Review

#1798 fix: pass environment variables to server
  src/api/services/import.js
Labels: Ready For Review

#1799 To avoid sending an unauthorized header to api.istex.fr
  src/app/js/lib/fetch.js
Labels: Ready For Review

#1801 Fix(precomputed): Handle logs and reception from webhook
  src/api/controller/api/precomputed.js
  src/api/controller/webhook.js
  src/api/services/precomputed/precomputed.js
  src/api/workers/precomputer.js
Labels: Ready For Review

#1803 introduce [dedupe] in all loaders
  package-lock.json
  package.json
  workers/loaders/atom.ini
  workers/loaders/corpus.ini
  workers/loaders/csv-comma.ini
  workers/loaders/csv-semicolon.ini
  workers/loaders/csv.ini
  workers/loaders/doi-list.ini
  workers/loaders/json-conditor.ini
  workers/loaders/json-datacite.ini
  workers/loaders/json-import.ini
  workers/loaders/json-inspirehep.ini
  workers/loaders/json-istex.ini
  workers/loaders/json-lines.ini
  workers/loaders/json-lodex.ini
  workers/loaders/json-optimized.ini
  workers/loaders/json-protege-resolver.ini
  workers/loaders/json-protege.ini
  workers/loaders/json-report.ini
  workers/loaders/json-wordpress.ini
  workers/loaders/json.ini
  workers/loaders/mods.ini
  workers/loaders/rdf.ini
  workers/loaders/rss.ini
  workers/loaders/skos.ini
  workers/loaders/tar-gz.ini
  workers/loaders/tei-persee.ini
  workers/loaders/tei.ini
  workers/loaders/tsv-double-quotes.ini
  workers/loaders/tsv-wos.ini
  workers/loaders/tsv.ini
  workers/loaders/xml.ini
  workers/loaders/zip-raw.ini
  workers/loaders/zip.ini
Labels: Ready For Review

#1808 Fix missing and bad width on vega and vega-lite
  src/app/js/formats/vega-lite/component/vega-lite-component/VegaLiteComponent.js
  src/app/js/formats/vega/component/vega-component/VegaComponent.js
Labels: Ready For Review

#1809 Fixes sorting and filtering issue for all formats that use source/tar…
  packages/ezsLodex/src/reduceQuery.js
  packages/ezsLodex/src/reducers/count.js
  packages/ezsLodex/src/reducers/distinct.js
  packages/ezsLodex/src/reducers/graph.js
  packages/ezsLodex/src/reducers/groupby.js
  packages/ezsLodex/src/reducers/keys.js
  packages/ezsLodex/src/reducers/max.js
  packages/ezsLodex/src/reducers/merge.js
  packages/ezsLodex/src/reducers/min.js
  packages/ezsLodex/src/reducers/pairing.js
  packages/ezsLodex/src/reducers/stats.js
  packages/ezsLodex/src/reducers/total.js
  packages/ezsLodex/src/reducers/ventilate.js
Labels: Ready For Review

#1810 Use routine to filter precomputed data
  config.json
  packages/ezsLodex/src/buildContext.js
  packages/ezsLodex/src/filterPrecomputed.js
  packages/ezsLodex/src/index.js
  packages/ezsLodex/src/runQuery.js
  packages/transformers/src/operations/PRECOMPUTED.js
  src/api/services/getDocumentTransformer.js
  src/api/services/publishCharacteristics.js
  src/api/services/publishCharacteristics.spec.js
  src/app/custom/routines/routines-precomputed-catalog.json
  src/app/js/fields/sourceValue/SourceValuePrecomputed.js
  src/app/js/fields/wizard/RoutineCatalog.js
  src/app/js/formats/sagas.js
  src/app/js/formats/sagas.spec.js
  src/app/js/lib/getDocumentTransformer.js
  src/common/getDocumentTransformer.js
  workers/routines/graph-by-precomputed.ini
  workers/routines/tree-by-precomputed.ini
Labels: Work In Progress
