Repository Inist-CNRS/lodex, pull requests merged in 2024-12, with the labels that each got.

#2239 Update translations.tsv
  src/app/custom/translations.tsv
Labels: 👷‍♂️ Ready For Review

#2236 button primary, secondary,button shadow for lodex composents
  src/app/custom/themes/istex/css/istex-internalclass.css
  src/app/custom/themes/istex/css/istex-linksclass.css
  src/app/custom/themes/istex/css/istex.css
Labels: 👷‍♂️ Ready For Review

#2244 refactor(theme istex): font size and line-height
  src/app/custom/themes/istex/css/istex-internalclass.css
  src/app/custom/themes/istex/css/istex-linksclass.css
  src/app/custom/themes/istex/css/istex.css
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design

#2258 Update Readme.md
  src/app/custom/themes/istex/Readme.md
Labels: 👷‍♂️ Ready For Review

#2265 Titre des blocs des listes de collections ne sont plus en gras
  src/app/custom/themes/istex-legacy/css/istex.css
Labels: 👷‍♂️ Ready For Review

#2267 Update Cartography.js
  src/app/js/formats/vega-lite/models/Cartography.js
Labels: 👷‍♂️ Ready For Review

#2266 bannieres et triptyque charte istex
  src/app/custom/themes/istex/Readme.md
  src/app/custom/themes/istex/css/istex-internalclass.css
  src/app/custom/themes/istex/css/istex-linksclass.css
Labels: 👷‍♂️ Ready For Review

#2276 Fix(data): Set page to 1 when filtering data
  cypress/e2e/phase_1/publication.cy.js
  cypress/fixtures/dataset/twoPagesForFilterTests.json
  src/app/js/admin/parsing/ParsingResult.js
Labels: 👷‍♂️ Ready For Review

#2280 fix test:unit:watch to pass on ubuntu 24
  jest.config.js
  package.json
  packages/ezsLodex/test/mongoQueries.spec.js
Labels: 👷‍♂️ Ready For Review

#2281 Fix(subresource): Add back button for ark resources
  src/app/js/public/resource/Resource.js
  src/app/js/public/resource/Resource.spec.js
  src/test-utils.js
Labels: 👷‍♂️ Ready For Review

#2277 Fix(facet): Reset facet page when filtering facets by name
  cypress/e2e/phase_3/search.cy.js
  cypress/fixtures/dataset/book_summary.csv
  cypress/support/searchDrawer.js
  src/app/js/public/facet/FacetValueList.js
Labels: 👷‍♂️ Ready For Review

#2274 Fix(enrichment): Debounce the number of calls to preview when filling advanced rule input
  cypress/e2e/phase_2/enrichment.cy.js
  src/app/js/admin/enrichment/EnrichmentForm.js
Labels: 👷‍♂️ Ready For Review, 🐛 Major defect

#2275 introduce matomo for Inist theme (like istex theme)
  src/app/custom/themes/inist/index.ejs
  src/app/custom/themes/inist/lodex-theme.json
Labels: 👷‍♂️ Ready For Review

#2273 avoid file write permissions error
  docker-compose.yml
Labels: 👷‍♂️ Ready For Review

#2283 2186 launch all enrichment
  src/api/controller/api/enrichment.js
  src/api/controller/api/enrichment.spec.js
  src/api/services/enrichment/enrichment.js
  src/app/custom/translations.tsv
  src/app/js/admin/enrichment/EnrichmentList.js
  src/app/js/admin/enrichment/index.js
  src/app/js/admin/enrichment/sagas.js
  src/app/js/user/index.js
Labels: 👷‍♂️ Ready For Review

#2288 2172: fix transformer validation
  src/common/validateFields.js
  src/common/validateFields.spec.js
Labels: 👷‍♂️ Ready For Review

#2287 2188 confirm enrichment deletion
  src/app/custom/translations.tsv
  src/app/js/admin/enrichment/DeleteEnrichmentButton.js
  src/app/js/admin/enrichment/DeleteEnrichmentButton.spec.js
  src/app/js/admin/enrichment/EnrichmentForm.js
  src/app/js/admin/enrichment/EnrichmentForm.spec.js
  src/app/js/admin/upload/PopupConfirmUpload.js
  src/app/js/admin/upload/PopupConfirmUpload.spec.js
  src/app/js/admin/upload/Upload.js
  src/app/js/lib/components/ConfirmPopup.js
  src/app/js/lib/components/ConfirmPopup.spec.js
Labels: 👷‍♂️ Ready For Review
