Repository Inist-CNRS/lodex, pull requests merged in 2024-06, with the labels that each got.

#2023 Add a button to go to admin page from the root-admin
  src/app/js/root-admin/Tenants.js
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design

#2022 istexTheme integration : first PR and commit in dev mode configuration (vscode wsl ubuntu docker) - historical moment !
  src/app/custom/themes/istex/istexTheme.js
Labels: 👷‍♂️ Ready For Review

#2027 Move template variables into the LODEX dynamic config
  config.json
  configTenant.json
  src/api/controller/api/themes.js
  src/api/controller/front.js
  src/api/models/front.js
  src/api/models/themes.js
  src/app/custom/themes/default/lodex-theme.json
  src/app/custom/themes/inist/lodex-theme.json
  src/app/custom/themes/istex-legacy/lodex-theme.json
  src/app/custom/themes/istex/lodex-theme.json
  src/app/custom/themes/nougat/lodex-theme.json
  src/app/custom/themes/void/lodex-theme.json
  src/app/js/embeddedIstexSummary/index.js
  src/app/js/public/hook/useTheme.js
Labels: 👷‍♂️ Ready For Review

#2021 Treemap format
  src/app/custom/translations.tsv
  src/app/js/formats/formats.js
  src/app/js/formats/utils/chartsUtils.js
  src/app/js/formats/utils/components/vega-component/VegaComponent.js
  src/app/js/formats/utils/dataSet.js
  src/app/js/formats/vega/component/tree-map/TreeMapAdmin.js
  src/app/js/formats/vega/component/tree-map/TreeMapData.js
  src/app/js/formats/vega/component/tree-map/TreeMapView.js
  src/app/js/formats/vega/component/tree-map/index.js
  src/app/js/formats/vega/models/TreeMap.js
  src/app/js/formats/vega/models/json/tree_map.vg.json
Labels: 👷‍♂️ Ready For Review

#2043 Update theme to fix mistake and forgotten change
  src/api/models/front.js
  src/api/models/themes.js
  src/app/admin.ejs
  src/app/custom/themes/default/index.ejs
  src/app/custom/themes/default/lodex-theme.json
  src/app/custom/themes/inist/index.ejs
  src/app/custom/themes/inist/lodex-theme.json
  src/app/custom/themes/istex-legacy/index.ejs
  src/app/custom/themes/istex-legacy/lodex-theme.json
  src/app/custom/themes/istex/index.ejs
  src/app/custom/themes/istex/lodex-theme.json
  src/app/custom/themes/nougat/lodex-theme.json
  src/app/custom/themes/void/lodex-theme.json
  src/app/root-admin.ejs
Labels: 👷‍♂️ Ready For Review

#2049 2048-14054-probleme-daffichage-graph-a-bulles-avec-themes-inist-istex
  src/app/custom/themes/inist/css/inist-styles.css
  src/app/custom/themes/istex/css/istex.css
Labels: 👷‍♂️ Ready For Review

#2065 Backoffice ux accordion
  src/app/js/formats/chart/asterPlotChart/AsterPlotChartAdmin.js
  src/app/js/formats/chart/bubbleChart/BubbleAdmin.js
  src/app/js/formats/chart/clustered-chart/ClusteredChartAdmin.js
  src/app/js/formats/chart/fieldClone/FieldCloneAdmin.js
  src/app/js/formats/chart/hierarchy/HierarchyAdmin.js
  src/app/js/formats/chart/network/NetworkAdmin.js
  src/app/js/formats/chart/parallel-coordinates/ParallelCoordinatesChartAdmin.js
  src/app/js/formats/chart/streamgraph/StreamgraphAdmin.js
  src/app/js/formats/lodex/field/LodexFieldAdmin.js
  src/app/js/formats/other/istexCitation/IstexCitationAdmin.js
  src/app/js/formats/other/istexSummary/IstexSummaryAdmin.js
  src/app/js/formats/other/json/JsonDebugAdmin.js
  src/app/js/formats/other/resources-grid/ResourcesGridAdmin.js
  src/app/js/formats/other/table/paginated/PaginatedTableAdmin.js
  src/app/js/formats/other/table/unpaginated/UnPaginatedTableAdmin.js
  src/app/js/formats/other/trello-timeline/TrelloTimelineAdmin.js
  src/app/js/formats/text/code/CodeAdmin.js
  src/app/js/formats/text/ejs/EJSAdmin.js
  src/app/js/formats/text/emphased-number/EmphasedNumberAdmin.js
  src/app/js/formats/text/identifier-badge/IdentifierBadgeAdmin.js
  src/app/js/formats/text/latex/LatexAdmin.js
  src/app/js/formats/text/list/ListAdmin.js
  src/app/js/formats/text/markdown/modal/MarkdownModalAdmin.js
  src/app/js/formats/text/paragraph/ParagraphAdmin.js
  src/app/js/formats/text/sentence/SentenceAdmin.js
  src/app/js/formats/text/sparql/SparqlTextField/SparqlAdmin.js
  src/app/js/formats/text/title/TitleAdmin.js
  src/app/js/formats/url/DefaultUrlAdmin.js
  src/app/js/formats/url/image/ImageAdmin.js
  src/app/js/formats/url/link-image/LinkImageAdmin.js
  src/app/js/formats/url/pdf/PDFAdmin.js
  src/app/js/formats/utils/components/default-format/DefaultAdmin.js
  src/app/js/formats/utils/components/field-set/FormatFieldSetPreview.js
  src/app/js/formats/utils/components/field-set/FormatFieldSets.js
  src/app/js/formats/utils/components/field-set/FormatGroupedFieldSet.js
  src/app/js/formats/vega-lite/VegaLiteAdmin.js
  src/app/js/formats/vega-lite/component/bar-chart/BarChartAdmin.js
  src/app/js/formats/vega-lite/component/bubble-plot/BubblePlotAdmin.js
  src/app/js/formats/vega-lite/component/cartography/CartographyAdmin.js
  src/app/js/formats/vega-lite/component/heatmap/HeatMapAdmin.js
  src/app/js/formats/vega-lite/component/pie-chart/PieChartAdmin.js
  src/app/js/formats/vega/component/flow-map/FlowMapAdmin.js
  src/app/js/formats/vega/component/radar-chart/RadarChartAdmin.js
  src/app/js/formats/vega/component/tree-map/TreeMapAdmin.js
Labels: 👩‍🎨 UX Design

#2038 refactor(global css + class lodex internes)
  .gitignore
  src/app/custom/themes/istex/Readme.md
  src/app/custom/themes/istex/charteIstex.html
  src/app/custom/themes/istex/css/istex-internalclass.css
  src/app/custom/themes/istex/css/istex.css
  src/app/custom/themes/istex/img/galaxie-istex-1.jpg
  src/app/custom/themes/istex/img/galaxie-istex-2.jpg
  src/app/custom/themes/istex/img/galaxie-istex-3.jpg
  src/app/custom/themes/istex/img/galaxie-tdm.jpg
  src/app/custom/themes/istex/img/right-arrow.png
  src/app/custom/themes/istex/img/svgfond.png
  src/app/custom/themes/istex/img/svgfond.svg
Labels: 👷‍♂️ Ready For Review

#2076 theme voscouleurs personnalisable en ligne
  config.json
  src/app/custom/themes/voscouleurs/android-chrome-192x192.png
  src/app/custom/themes/voscouleurs/android-chrome-512x512.png
  src/app/custom/themes/voscouleurs/apple-touch-icon.png
  src/app/custom/themes/voscouleurs/browserconfig.xml
  src/app/custom/themes/voscouleurs/css/styles.css
  src/app/custom/themes/voscouleurs/favicon-16x16.png
  src/app/custom/themes/voscouleurs/favicon-32x32.png
  src/app/custom/themes/voscouleurs/font/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/Montserrat-VariableFont_wght.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/OFL.txt
  src/app/custom/themes/voscouleurs/font/Montserrat/README.txt
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-Black.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-BlackItalic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-Bold.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-BoldItalic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-ExtraBold.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-ExtraLight.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-ExtraLightItalic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-Italic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-Light.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-LightItalic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-Medium.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-MediumItalic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-Regular.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-SemiBold.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-SemiBoldItalic.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-Thin.ttf
  src/app/custom/themes/voscouleurs/font/Montserrat/static/Montserrat-ThinItalic.ttf
  src/app/custom/themes/voscouleurs/humans.txt
  src/app/custom/themes/voscouleurs/img/cea.jpg
  src/app/custom/themes/voscouleurs/index.ejs
  src/app/custom/themes/voscouleurs/lodex-theme.json
  src/app/custom/themes/voscouleurs/mstile-150x150.png
  src/app/custom/themes/voscouleurs/readme.md
  src/app/custom/themes/voscouleurs/robots.txt
  src/app/custom/themes/voscouleurs/site.webmanifest
  src/app/custom/themes/voscouleurs/voscouleursTheme.js
Labels: 👷‍♂️ Ready For Review
