Repository Inist-CNRS/lodex, pull requests merged in 2024-07, with the labels that each got.

#2084 Add missing Typography in preview
  src/app/js/formats/utils/components/field-set/FormatFieldSetPreview.js
Labels: 👷‍♂️ Ready For Review, 🤖 Trivial defect, 👩‍🎨 UX Design

#2079 Correctly handle colors change on treemap
  src/app/js/formats/vega/component/tree-map/TreeMapAdmin.js
Labels: 👷‍♂️ Ready For Review

#2080 Routine builder
  src/app/custom/translations.tsv
  src/app/js/fields/FieldRepresentation.js
  src/app/js/fields/sourceValue/SourceValuePrecomputed.js
  src/app/js/fields/sourceValue/SourceValueRoutine.js
  src/app/js/fields/wizard/RoutineCatalogAutocomplete.js
  src/app/js/propTypes.js
Labels: 👷‍♂️ Ready For Review

#2089 Improve routine builder
  src/app/custom/translations.tsv
  src/app/js/fields/sourceValue/SourceValueRoutine.js
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design

#2090 Root panel improvement
  cypress/e2e/phase_4/rootAdmin.cy.js
  package-lock.json
  package.json
  src/api/controller/rootAdmin.js
  src/app/js/root-admin/CreateTenantDialog.js
  src/app/js/root-admin/DeleteTenantDialog.js
  src/app/js/root-admin/LoginForm.js
  src/app/js/root-admin/NameField.js
  src/app/js/root-admin/SystemLoad.js
  src/app/js/root-admin/Tenants.js
  src/app/js/root-admin/UpdateTenantDialog.js
  src/app/js/root-admin/index.js
  src/app/js/root-admin/rootAdminUtils.js
  src/app/root-admin.ejs
  src/common/tools/tenantTools.js
Labels: 👷‍♂️ Ready To Merge, 👩‍🎨 UX Design

#2085 Make treemap compatible with flat data
  src/app/custom/translations.tsv
  src/app/js/formats/utils/components/field-set/FormatFieldSetPreview.js
  src/app/js/formats/vega/component/tree-map/TreeMapAdmin.js
  src/app/js/formats/vega/component/tree-map/TreeMapData.js
  src/app/js/formats/vega/component/tree-map/TreeMapView.js
  src/app/js/formats/vega/models/TreeMap.js
Labels: 👷‍♂️ Ready To Merge

#2094 Theme config autocomplete
  src/api/models/themes.js
  src/app/custom/themes/voscouleurs/lodex-theme.json
  src/app/js/admin/configTenant/ConfigTenantForm.js
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design

#2101 Add size selection for markdown modal size
  src/app/custom/translations.tsv
  src/app/js/formats/text/markdown/modal/MarkdownModalAdmin.js
  src/app/js/formats/text/markdown/modal/MarkdownModalView.js
Labels: 👷‍♂️ Ready To Merge

#2106 Fail-safe to avoid crash on ejs rendering error
  src/api/models/front.js
Labels: 👷‍♂️ Ready For Review, 🐛 Major defect

#2095 documentation des thèmes
  src/app/custom/themes/istex/Readme.md
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design

#2096 documentation config theme Voscouleurs #2092
  src/app/custom/themes/istex/lodex-theme.json
  src/app/custom/themes/voscouleurs/index.ejs
  src/app/custom/themes/voscouleurs/lodex-theme.json
  src/app/custom/themes/voscouleurs/voscouleursTheme.js
Labels: 👷‍♂️ Ready For Review

#2103 Increas container size
  src/app/custom/themes/default/css/styles.css
  src/app/custom/themes/default/index.ejs
  src/app/js/public/App.js
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design

#2104 fix(theme inist header): le lien sur le titre du header renvoie sur home
  src/app/custom/themes/inist/css/inist-styles.css
  src/app/custom/themes/inist/index.ejs
  src/app/custom/themes/inist/lodex-theme.json
Labels: 👷‍♂️ Ready For Review

#2105 graph summary page replace capitalize to none for textTransform
  src/app/js/public/graph/GraphSummary.js
Labels: 👷‍♂️ Ready For Review

#2108 2107 theme istex dev migration vers theme istex
  src/app/custom/themes/istex-devclassinterne/howToMigrate.md
  src/app/custom/themes/istex-devclassinterne/lodex-theme.json
Labels: 👷‍♂️ Ready For Review
