Repository Inist-CNRS/lodex, pull requests merged in 2024-11, with the labels that each got.

#2199 ✨ Corrections visuelles thème istex-legacy
  src/app/custom/themes/istex-legacy/css/istex.css
Labels: 👷‍♂️ Ready to go

#2152 septembre16-20 custom/themes
  src/app/custom/themes/inist/css/inist-styles.css
  src/app/custom/themes/istex/css/istex-internalclass.css
  src/app/custom/themes/istex/css/istex-linksclass.css
  src/app/custom/themes/istex/css/istex.css
  src/app/custom/themes/voscouleurs/css/styles.css
  src/app/custom/themes/voscouleurs/font/Quicksand/OFL.txt
  src/app/custom/themes/voscouleurs/font/Quicksand/OFL.txt:Zone.Identifier
  src/app/custom/themes/voscouleurs/font/Quicksand/Quicksand-VariableFont_wght.ttf
  src/app/custom/themes/voscouleurs/font/Quicksand/Quicksand-VariableFont_wght.ttf:Zone.Identifier
  src/app/custom/themes/voscouleurs/font/Quicksand/README.txt
  src/app/custom/themes/voscouleurs/font/Quicksand/README.txt:Zone.Identifier
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Bold.ttf
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Bold.ttf:Zone.Identifier
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Light.ttf
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Light.ttf:Zone.Identifier
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Medium.ttf
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Medium.ttf:Zone.Identifier
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Regular.ttf
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-Regular.ttf:Zone.Identifier
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-SemiBold.ttf
  src/app/custom/themes/voscouleurs/font/Quicksand/static/Quicksand-SemiBold.ttf:Zone.Identifier
  src/app/custom/themes/voscouleurs/index.ejs
  src/app/custom/themes/voscouleurs/lodex-theme.json
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design

#2228 style(theme voscouleurs): etiquette (titre) graph personal color
  src/app/custom/themes/voscouleurs/css/styles.css
  src/app/custom/themes/voscouleurs/defaultTheme.js
  src/app/custom/themes/voscouleurs/lodex-theme.json
Labels: 👷‍♂️ Ready For Review
