Repository Inist-CNRS/lodex, pull requests merged in 2025-03, with the labels that each got.

#2633 Fix(annotation): Redirect to datagrid when saving an annotation
  cypress/e2e/phase_4/annotation.cy.js
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/js/admin/annotations/hooks/useUpdateAnnotation.js
Labels: 👷‍♂️ Ready For Review

#2631 2611 fix column selection
  src/app/js/admin/annotations/AnnotationList.js
  src/app/js/admin/parsing/ParsingResult.js
  src/app/js/lib/hooks/useDatagridSelection.js
Labels: 👷‍♂️ Ready For Review

#2634 2529 better save button
  src/app/js/admin/annotations/details/AnnotationForm.js
  src/app/js/admin/configTenant/ConfigTenantForm.js
  src/app/js/fields/wizard/Actions.js
  src/app/js/lib/components/SaveButton.js
  src/app/js/lib/components/SaveButton.spec.js
Labels: 👷‍♂️ Ready For Review

#2639 Fix(network): Show mouse icon for network graphs
  src/app/js/formats/chart/network/NetworkView.js
Labels: 👷‍♂️ Ready For Review

#2645 Fix(field): Show annotation disabled icon next to field title
  src/app/js/fields/FieldGrid.js
Labels: 👷‍♂️ Ready For Review

#2647 2550 simplify annotation form step
  cypress/support/annotation.js
  src/app/custom/translations.tsv
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/NextButton.js
  src/app/js/annotation/NextButton.spec.js
  src/app/js/annotation/PreviousButton.js
  src/app/js/annotation/PreviousButton.spec.js
  src/app/js/annotation/fields/KindField.js
  src/app/js/annotation/fields/KindField.spec.js
  src/app/js/annotation/fields/TargetField.js
  src/app/js/annotation/fields/TargetField.spec.js
  src/app/js/annotation/steps.js
Labels: 👷‍♂️ Ready For Review

#2650 Fix(front): List bullet alignment is now on top of item
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/formats/text/list/ListView.js
  src/app/js/formats/utils/components/default-format/DefaultView.js
Labels: 👷‍♂️ Ready For Review

#2654 2506 replace comment by annotate
  cypress/e2e/phase_4/annotation.cy.js
  cypress/support/annotation.js
  src/app/custom/translations.tsv
  src/app/js/annotation/AnnotationCommentStep.js
  src/app/js/annotation/AnnotationCommentStep.spec.js
  src/app/js/annotation/AnnotationList.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/CreateAnnotationTitle.js
  src/app/js/annotation/CreateAnnotationTitle.spec.js
  src/app/js/annotation/fields/TargetField.js
  src/app/js/annotation/fields/TargetField.spec.js
Labels: 👷‍♂️ Ready For Review

#2653 Fix(autocomplete): Do not allow new values if not free solo
  src/app/js/annotation/fields/ProposedValueFieldList.js
  src/app/js/lib/components/AutocompleteField.js
  src/app/js/lib/components/AutocompleteField.spec.js
  src/app/js/lib/components/AutocompleteMultipleField.js
  src/app/js/lib/components/AutocompleteMutipleField.spec.js
Labels: 👷‍♂️ Ready For Review

#2659 2525 annotation on modified value
  src/app/custom/translations.tsv
  src/app/js/annotation/AnnotationCommentStep.js
  src/app/js/annotation/AnnotationCommentStep.spec.js
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/fields/TargetField.js
  src/app/js/annotation/fields/TargetField.spec.js
  src/app/js/formats/formats.js
  src/app/js/formats/index.js
Labels: 👷‍♂️ Ready For Review

#2663 2621: fix deletion wording when only one annotation selected
  src/app/custom/translations.tsv
Labels: 👷‍♂️ Ready For Review

#2657 2656: mark notificationEmail as nullable
  configTenant.json
  src/app/js/admin/configTenant/ConfigTenantForm.js
  src/app/js/admin/configTenant/ConfigTenantForm.spec.js
Labels: 👷‍♂️ Ready For Review

#2666 15.4.2
  Makefile
  package-lock.json
  package.json
Labels: 👷‍♂️ Ready For Review

#2668 Feat(annotation): Do not enforce confirm if form is not dirty
  cypress/support/annotation.js
  src/app/custom/translations.tsv
  src/app/js/annotation/AnnotationList.js
  src/app/js/annotation/AnnotationList.spec.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/fields/FieldGrid.js
  src/app/js/fields/FieldRepresentation.js
Labels: 👷‍♂️ Ready For Review

#2669 2575: properly render null facet value
  src/app/js/public/facet/FacetList.js
  src/app/js/public/facet/FacetValueItem.js
  src/app/js/public/facet/FacetValueItem.spec.js
Labels: 👷‍♂️ Ready For Review

#2672 Fix(annotation): Add history when creating an annotation for a field with no value
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
Labels: 👷‍♂️ Ready For Review

#2678 2674 fix chart link
  src/app/js/admin/annotations/ResourceUriCell.js
  src/app/js/admin/annotations/ResourceUriCell.spec.js
  src/app/js/admin/annotations/details/AnnotationHeader.js
  src/app/js/admin/annotations/details/AnnotationHeader.spec.js
Labels: 👷‍♂️ Ready For Review

#2679 2648: update shouldDisplayFIeld to handle clonedField properly
  src/app/js/fields/shouldDisplayField.js
  src/app/js/fields/shouldDisplayField.spec.js
  src/app/js/public/Property/index.js
Labels: 👷‍♂️ Ready For Review

#2667 2524: Add getReadableValue option to format, implement logic for Uri format
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/formats/index.js
  src/app/js/formats/url/uri/UriView.js
  src/app/js/formats/url/uri/index.js
  src/app/js/formats/utils/components/default-format/DefaultView.js
  src/app/js/formats/utils/components/default-format/index.js
  src/app/js/public/Property/index.js
  src/app/js/public/graph/Graph.js
Labels: 👷‍♂️ Ready For Review

#2685 2563 prefilled proposed value
  src/app/js/annotation/AnnotationCommentStep.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/fields/ProposedValueField.js
  src/app/js/annotation/fields/ProposedValueField.spec.js
  src/app/js/annotation/fields/ProposedValueFieldText.js
  src/app/js/annotation/fields/ProposedValueFieldText.spec.js
  src/app/js/lib/components/TextField.js
  src/app/js/lib/components/TextField.spec.js
Labels: 👷‍♂️ Ready For Review

#2695 2560 convert initialValue to string on change
  src/app/js/annotation/AnnotationCommentStep.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/PreviousButton.js
  src/app/js/annotation/fields/TargetField.js
  src/app/js/annotation/fields/ValueField.js
Labels: 👷‍♂️ Ready For Review

#2693 2583 ux admin contributor
  src/app/custom/translations.tsv
  src/app/js/admin/configTenant/ConfigTenantForm.js
  src/app/js/admin/configTenant/ConfigTenantForm.spec.js
Labels: 👷‍♂️ Ready For Review

#2696 2688 fix captcha validation
  src/app/js/admin/configTenant/ConfigTenantForm.js
  src/app/js/admin/configTenant/ConfigTenantForm.spec.js
Labels: 👷‍♂️ Ready For Review

#2684 2655 remember seen document
  src/app/js/public/resource/Resource.js
  src/app/js/public/resource/Resource.spec.js
  src/app/js/public/resource/useRememberVisit.js
  src/app/js/public/resource/useRememberVisit.spec.js
  src/app/js/public/search/SearchResult.js
  src/app/js/public/search/SearchResult.spec.js
Labels: 👷‍♂️ Ready For Review

#2686 Feat(annotation): Add button to redirect to dataset with resource uri filtered from annotation detail
  cypress/e2e/phase_4/annotation.cy.js
  cypress/fixtures/annotations/film-many-annotations.json
  eslint.config.mjs
  src/app/custom/translations.tsv
  src/app/js/admin/annotations/AnnotationDetail.spec.js
  src/app/js/admin/annotations/ResourceUriCell.js
  src/app/js/admin/annotations/details/AnnotationForm.js
  src/app/js/admin/annotations/details/AnnotationForm.spec.js
  src/app/js/admin/annotations/details/AnnotationHeader.js
  src/app/js/admin/annotations/details/AnnotationHeader.spec.js
  src/app/js/admin/annotations/helpers/field.js
  src/app/js/admin/annotations/helpers/resourceType.js
  src/app/js/admin/parsing/ParsingResult.js
  src/app/js/admin/parsing/ParsingResult.spec.js
  src/app/js/annotation/useGetFieldAnnotation.js
  src/app/js/public/Property/index.js
Labels: 👷‍♂️ Ready For Review

#2697 Feat(annotation): Show user provided values in the annotation detail
  src/app/custom/translations.tsv
  src/app/js/admin/annotations/details/AnnotationProposedValue.js
  src/app/js/admin/annotations/details/AnnotationProposedValue.spec.js
  src/app/js/admin/annotations/details/UserProvidedValueIcon.js
Labels: 👷‍♂️ Ready For Review

#2687 2594 controlled accordion
  cypress/e2e/phase_4/annotation.cy.js
  src/app/custom/translations.tsv
  src/app/js/annotation/AnnotationList.js
  src/app/js/annotation/AnnotationList.spec.js
  src/app/js/lib/components/icons/CloseAllIcon.js
  src/app/js/lib/components/icons/OpenAllIcon.js
Labels: 👷‍♂️ Ready For Review

#2707 Feat(search): Add support for default sort order
  cypress/e2e/phase_3/search.cy.js
  src/api/controller/api/field.js
  src/api/controller/api/field.spec.js
  src/app/custom/translations.tsv
  src/app/js/admin/Search/SearchForm.js
  src/app/js/admin/api/field.js
  src/app/js/fields/selectors.js
  src/app/js/public/search/SearchResultSort.js
  src/app/js/public/search/reducer.js
  src/app/js/public/search/sagas.js
  src/app/js/user/index.js
Labels: 👷‍♂️ Ready For Review

#2699 2602 wordings
  cypress/e2e/phase_4/annotation.cy.js
  cypress/support/annotation.js
  src/app/custom/translations.tsv
  src/app/js/admin/annotations/CellWithTooltip.js
  src/app/js/admin/annotations/ResourceTitleCell.js
  src/app/js/admin/annotations/ResourceUriCell.js
  src/app/js/annotation/AnnotationCommentStep.js
  src/app/js/annotation/AnnotationList.js
  src/app/js/annotation/AnnotationList.spec.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/HistoryDrawer.spec.js
  src/app/js/annotation/OpenHistoryButton.js
  src/app/js/annotation/OpenHistoryButton.spec.js
  src/app/js/annotation/fields/ValueField.js
  src/app/js/lib/components/ConfirmPopup.js
Labels: 👷‍♂️ Ready For Review

#2711 Fix(config): Config merge is no longer overrided in memory
  src/api/controller/api/annotation.js
  src/api/controller/api/annotation.spec.js
  src/api/controller/api/recaptcha.js
  src/api/controller/front.js
  src/api/controller/index.js
  src/app/custom/translations.tsv
  src/app/js/admin/configTenant/ConfigTenantForm.js
Labels: 👷‍♂️ Ready For Review

#2705 2587 export selected columns
  cypress/e2e/phase_4/annotation.cy.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/api/controller/api/dump.js
  src/api/controller/api/dump.spec.js
  src/api/models/dataset.js
  src/api/models/dataset.spec.js
  src/app/custom/translations.tsv
  src/app/js/admin/Appbar/menu/AdvancedNestedMenu.js
  src/app/js/admin/dump/sagas.js
  src/app/js/admin/dump/sagas.spec.js
  src/app/js/public/ExportButton.js
  src/app/js/public/export/ExportDatasetButton.js
  src/app/js/public/export/ExportDatasetButton.spec.js
  src/app/js/user/index.js
  src/app/js/user/index.spec.js
Labels: 👷‍♂️ Ready For Review

#2713 2675: convert publishedDataset to use post
  src/api/controller/api/publishedDataset.js
  src/api/controller/api/publishedDataset.spec.js
  src/app/js/user/index.js
Labels: 👷‍♂️ Ready For Review

#2714 Fix(facet): Add count to facets and improve test speed
  jest.config.js
  package.json
  src/app/js/public/facet/FacetValueItem.js
  src/app/js/public/facet/FacetValueItem.spec.js
Labels: 👷‍♂️ Ready For Review, 👷‍♂️ Do Not Merge

#2719 Fix(settings): Allow users to save form when antispam filter is disabled after updating the config
  src/app/js/admin/configTenant/ConfigTenantForm.js
Labels: 👷‍♂️ Ready For Review

#2712 2563: change delete icon and add tooltip
  src/app/js/lib/components/TextField.js
Labels: 👷‍♂️ Ready For Review

#2720 fix(theme istex et voscouleurs): css semantisation annotation - css f…
  src/app/custom/themes/istex/css/istex.css
  src/app/custom/themes/voscouleurs/css/styles.css
Labels: 👷‍♂️ Ready For Review

#2721 Fix(export): Replace Select by Autocomplete for dataset export
  src/app/js/public/export/ExportDatasetButton.js
  src/app/js/public/export/ExportDatasetButton.spec.js
Labels: 👷‍♂️ Ready For Review

#2723 2675 search by annotated by me
  cypress/e2e/phase_4/annotation.cy.js
  cypress/support/searchDrawer.js
  src/api/controller/api/publishedDataset.js
  src/api/controller/api/publishedDataset.spec.js
  src/api/models/getPublishedDatasetFilter.js
  src/api/models/getPublishedDatasetFilter.spec.js
  src/api/models/publishedDataset.js
  src/api/models/publishedDataset.spec.js
  src/app/custom/translations.tsv
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/annotation/annotationStorage.js
  src/app/js/annotation/annotationStorage.spec.js
  src/app/js/annotation/useCreateAnnotation.js
  src/app/js/annotation/useCreateAnnotation.spec.js
  src/app/js/annotation/useGetFieldAnnotation.spec.js
  src/app/js/public/search/MyAnnotationsFilter.js
  src/app/js/public/search/Search.js
  src/app/js/public/search/SearchSearchBar.js
  src/app/js/public/search/reducer.js
  src/app/js/public/search/reducer.spec.js
  src/app/js/public/search/sagas.js
  src/app/js/public/search/sagas.spec.js
Labels: 👷‍♂️ Ready For Review

#2722 Fix(search): Add loading indicator when an update is in flight for search admin
  src/app/js/admin/Search/SearchAutocomplete.js
  src/app/js/admin/Search/SearchForm.js
  src/app/js/admin/Search/SearchForm.spec.js
  src/app/js/admin/Search/usePatchFieldOverview.js
  src/app/js/admin/Search/usePatchSortField.js
  src/app/js/admin/Search/usePatchSortOrder.js
Labels: 👷‍♂️ Ready For Review

#2726 Feat(field): Show empty fields if user can annotate
  src/app/js/fields/shouldDisplayField.js
  src/app/js/fields/shouldDisplayField.spec.js
  src/app/js/public/Property/index.js
  src/app/js/public/Property/index.spec.js
Labels: 👷‍♂️ Ready For Review

#2732 2545: reorder columns
  cypress/e2e/phase_4/annotation.cy.js
  cypress/fixtures/model/film-obsolete.json
  src/app/js/admin/annotations/AnnotationList.js
Labels: 👷‍♂️ Ready For Review

#2730 2725 allow empty initial value
  cypress/e2e/phase_3/search.cy.js
  src/app/js/admin/annotations/details/AnnotationItems.js
  src/app/js/annotation/AnnotationList.js
  src/app/js/annotation/AnnotationList.spec.js
  src/common/validator/annotation.validator.js
  src/common/validator/annotation.validator.spec.js
Labels: 👷‍♂️ Ready For Review

#2728 feat(field): Move annotation fields to its own tab
  cypress/e2e/phase_4/annotation.cy.js
  src/app/custom/translations.tsv
  src/app/js/fields/wizard/Actions.js
  src/app/js/fields/wizard/TabAnnotations.js
  src/app/js/fields/wizard/TabSemantics.js
  src/app/js/fields/wizard/index.js
Labels: 👷‍♂️ Ready For Review

#2733 enable an unused reducer
  config.json
  packages/ezsLodex/src/reducers/ventilate.js
  src/app/custom/routines/routines-catalog.json
  src/app/custom/translations.tsv
  workers/routines/ventilate-by.ini
Labels: 👷‍♂️ Ready For Review

#2734 2572 annotated filter
  cypress/support/searchDrawer.js
  src/api/controller/api/publishedDataset.js
  src/api/controller/api/publishedDataset.spec.js
  src/api/models/annotation.js
  src/app/custom/translations.tsv
  src/app/js/public/search/AnnotationsFilter.js
  src/app/js/public/search/Search.js
  src/app/js/public/search/SearchSearchBar.js
  src/app/js/public/search/reducer.js
  src/app/js/public/search/reducer.spec.js
  src/app/js/public/search/sagas.js
  src/app/js/public/search/sagas.spec.js
Labels: 👷‍♂️ Ready For Review

#2731 Feat(annotation): Add field to exported annotations
  src/api/controller/api/annotation.js
  src/api/controller/api/annotation.spec.js
  src/api/models/field.js
Labels: 👷‍♂️ Ready For Review

#2741 Fix(lodex): Various improvements on UX
  cypress/e2e/phase_4/annotation.cy.js
  src/app/custom/translations.tsv
  src/app/js/admin/parsing/ParsingResult.js
  src/app/js/annotation/AnnotationList.js
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/lib/components/icons/CloseAllIcon.js
  src/app/js/lib/components/icons/OpenAllIcon.js
  src/app/js/public/graph/Graph.js
Labels: 👷‍♂️ Ready For Review

#2750 Fix(annotation): Add support for list of string arrays for initialValue field
  src/app/js/annotation/fields/ValueField.js
  src/app/js/annotation/fields/ValueField.spec.js
Labels: 👷‍♂️ Ready For Review

#2751 2604 display contributor in front
  cypress/e2e/phase_4/annotation.cy.js
  cypress/support/annotation.js
  src/app/custom/translations.tsv
  src/app/js/annotation/AnnotationList.js
  src/app/js/annotation/AnnotationList.spec.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/fields/IsContributorNamePublicField.js
  src/app/js/annotation/useContributorCache.js
  src/app/js/annotation/useGetFieldAnnotation.spec.js
  src/common/validator/annotation.validator.js
  src/common/validator/annotation.validator.spec.js
Labels: 👷‍♂️ Ready For Review

#2755 Fix(ux): Improve search UX and translations
  cypress/e2e/phase_3/search.cy.js
  cypress/support/searchDrawer.js
  src/app/custom/translations.tsv
  src/app/js/fields/FieldRepresentation.js
  src/app/js/fields/wizard/index.js
  src/app/js/lib/components/searchbar/SearchBar.js
  src/app/js/public/dataset/AppliedDatasetFacetList.js
  src/app/js/public/dataset/DatasetSearchBar.js
  src/app/js/public/search/AnnotationsFilter.js
  src/app/js/public/search/AppliedSearchFacetList.js
  src/app/js/public/search/SearchResultSort.js
  src/app/js/public/search/SearchSearchBar.js
  src/app/js/public/search/VisitedResourcesFilter.js
  src/app/js/public/search/reducer.js
Labels: 👷‍♂️ Ready For Review

#2758 2754 fix filter combo
  src/api/controller/api/publishedDataset.js
  src/api/controller/api/publishedDataset.spec.js
  src/app/js/public/search/sagas.js
  src/app/js/public/search/sagas.spec.js
Labels: 👷‍♂️ Ready For Review

#2759 Fix(annotation): Sort annotation export by createdAt desc
  src/api/models/annotation.js
  src/api/models/annotation.spec.js
Labels: 👷‍♂️ Ready For Review

#2765 fix margin on remember me field
  src/app/js/annotation/fields/AuthorRememberMeField.js
Labels: 👷‍♂️ Ready For Review

#2779 chore(theme istex ): sidebar esp. entre élém. - pos. fleche ListePave
  src/app/custom/themes/istex/css/istex-internalclass.css
  src/app/custom/themes/istex/css/istex.css
Labels: 👷‍♂️ Ready For Review, 👩‍🎨 UX Design
