Repository Inist-CNRS/lodex, pull requests merged in 2025-01, with the labels that each got.

#2295 2167 enrichment retry errored line
  src/api/app.js
  src/api/controller/api/enrichment.js
  src/api/controller/api/enrichment.spec.js
  src/api/services/enrichment/enrichment.js
  src/api/services/enrichment/enrichment.spec.js
  src/api/workers/enricher.js
  src/api/workers/index.js
  src/app/custom/translations.tsv
  src/app/js/admin/enrichment/EnrichmentList.js
  src/app/js/admin/enrichment/index.js
  src/app/js/admin/enrichment/sagas.js
  src/app/js/user/index.js
Labels: 👷‍♂️ Ready For Review

#2297 Feat(graph): Add support for export as CSV
  cypress/.gitignore
  cypress/e2e/phase_4/graph_page.cy.js
  package-lock.json
  package.json
  src/app/custom/translations.tsv
  src/app/js/formats/utils/components/useVegaActions.js
  src/app/js/formats/utils/components/useVegaCsvExport.js
  src/app/js/formats/utils/components/vega-component/VegaComponent.js
  src/app/js/formats/utils/components/vega-lite-component/VegaLiteComponent.js
Labels: 👷‍♂️ Ready For Review

#2301 Feat(enrichment): Order execution to avoir error due to dependencies
  src/api/controller/api/enrichment.js
  src/api/services/orderEnrichmentsByDependencies.js
  src/api/services/orderEnrichmentsByDependencies.spec.js
Labels: 👷‍♂️ Ready For Review

#2298 Fix(facet): Do not display facets that are not available in the user language
  cypress.config.js
  cypress/.gitignore
  cypress/e2e/phase_3/search.cy.js
  cypress/support/bookSummary.js
  cypress/support/fields.js
  cypress/support/menu.js
  cypress/support/settings.js
  src/app/js/public/facet/FacetList.js
Labels: 👷‍♂️ Ready For Review

#2306 upgrade node to version 20
  Dockerfile
  Dockerfile.spec
  docker-compose.dev.yml
  docker-compose.spec.yml
Labels: 👷‍♂️ Ready For Review

#2299 Feat(admin): Select automatically field type when creating a new field
  src/app/js/fields/FieldToggleInternalScope.js
Labels: 👷‍♂️ Ready For Review

#2309 14.0.72
  Makefile
  package-lock.json
  package.json
Labels: 👷‍♂️ Ready For Review

#2310 2172: fix transformers validation
  src/app/js/fields/FieldToggleInternalScope.js
  src/common/validateFields.js
  src/common/validateFields.spec.js
Labels: 👷‍♂️ Ready For Review

#2312 2188: update confirm deletion description
  src/app/custom/translations.tsv
Labels: 👷‍♂️ Ready For Review

#2314 improve enrichment error message for lodash error
  src/api/services/enrichment/enrichment.js
Labels: 👷‍♂️ Ready For Review

#2292 Feat(admin): Provide ability to delete multiple fields at the same time
  cypress/e2e/phase_1/publication.cy.js
  src/api/models/field.js
  src/app/custom/translations.tsv
  src/app/js/admin/field/AddFieldButton.js
  src/app/js/admin/field/DeleteFieldsButton.js
  src/app/js/admin/field/FieldsEdit.js
  src/app/js/admin/preview/publication/sagas.js
  src/app/js/fields/FieldGrid.js
  src/app/js/fields/FieldRepresentation.js
  src/app/js/fields/index.js
  src/app/js/fields/sagas/index.js
  src/app/js/fields/sagas/removeFieldList.js
  src/app/js/fields/sagas/removeFieldList.spec.js
Labels: 👷‍♂️ Work In Progress

#2311 Fix(export): Add date to export
  cypress/e2e/phase_4/graph_page.cy.js
  src/app/js/formats/utils/components/useVegaCsvExport.js
Labels: 👷‍♂️ Ready For Review

#2313 Fix(enrichment): Add dataset columns to initial visited nodes
  src/api/controller/api/enrichment.js
  src/api/controller/api/enrichment.spec.js
  src/api/services/orderEnrichmentsByDependencies.js
  src/api/services/orderEnrichmentsByDependencies.spec.js
Labels: 👷‍♂️ Ready For Review

#2319 2172 fix fieldClone validation for all case
  src/app/js/fields/sourceValue/SourceValueToggle.js
  src/common/validateFields.js
  src/common/validateFields.spec.js
Labels: 👷‍♂️ Ready For Review

#2318 Feat(fields): Improve UX and deletion modal text
  .prettierrc
  jsconfig.json
  src/app/custom/translations.tsv
  src/app/js/admin/field/DeleteFieldsButton.js
  src/app/js/fields/FieldGrid.js
  src/app/js/fields/FieldRepresentation.js
Labels: 👷‍♂️ Ready For Review

#2321 Fix(search): Add support for more diacritics characters
  src/api/services/createDiacriticSafeContainRegex.js
  src/api/services/createDiacriticSafeContainRegex.spec.js
Labels: 👷‍♂️ Ready For Review

#2322 2315 reenable run on enrichment end
  src/api/app.js
  src/app/js/admin/enrichment/EnrichmentForm.js
  src/app/js/admin/enrichment/EnrichmentList.js
  src/app/js/admin/enrichment/EnrichmentStatus.js
  src/app/js/admin/enrichment/RunButton.js
  src/app/js/admin/enrichment/RunButton.spec.js
Labels: 👷‍♂️ Ready For Review

#2320 2167: fix enrichment call to properly pass retryFailedOnly properly
  src/api/services/enrichment/enrichment.js
  src/app/custom/translations.tsv
  src/app/js/admin/enrichment/EnrichmentForm.js
  src/app/js/admin/enrichment/EnrichmentList.js
Labels: 👷‍♂️ Ready For Review

#2343 Fix(graph): Disable CSV export if data does not match { _id, value } or { source, target, weight } formats
  cypress/e2e/phase_4/graph_page.cy.js
  src/app/js/formats/utils/components/useVegaCsvExport.js
Labels: 👷‍♂️ Ready For Review

#2342 Fix(facets): Clear facets filters when reseting the form
  cypress/e2e/phase_3/search.cy.js
  src/app/js/public/facet/FacetList.js
  src/app/js/public/facet/index.js
  src/app/js/public/facet/sagas.js
Labels: 👷‍♂️ Ready For Review

#2337 Fix(enrichment): Add confirm modal and better error handling when running all enrichments
  src/api/controller/api/enrichment.js
  src/api/services/orderEnrichmentsByDependencies.js
  src/app/custom/translations.tsv
  src/app/js/admin/enrichment/EnrichmentForm.js
  src/app/js/admin/enrichment/EnrichmentList.js
  src/app/js/admin/enrichment/index.js
  src/app/js/admin/enrichment/sagas.js
Labels: 👷‍♂️ Ready For Review

#2344 upgrade webpack and babel to latest versions
  package-lock.json
  package.json
Labels: 👷‍♂️ Ready For Review

#2349 Fix(facets): Reset facet filter when removing a single facet
  cypress/e2e/phase_3/search.cy.js
  src/app/js/public/facet/sagas.js
Labels: 👷‍♂️ Ready For Review

#2350 2172 fix cloned graph
  src/app/js/formats/chart/fieldClone/index.js
  src/app/js/formats/checkPredicate.js
  src/app/js/formats/checkPredicate.spec.js
Labels: 👷‍♂️ Ready For Review

#2336 Fix vulnerabilities
  .eslintrc.js
  eslint.config.mjs
  package-lock.json
  package.json
  src/api/services/fsHelpers.spec.js
  src/api/services/import.js
  src/api/services/precomputed/precomputed.js
  src/api/services/saveParsedStream-e2e.spec.js
  src/api/workers/tools.js
  src/app/custom/themes/istex-legacy/customTheme.js
  src/app/js/admin/Search/SearchForm.spec.js
  src/app/js/admin/parsing/sagas.spec.js
  src/app/js/admin/preview/Excerpt.js
  src/app/js/admin/publish/sagas.js
  src/app/js/admin/removedResources/ImportButton.js
  src/app/js/embeddedIstexSummary/FieldProvider.js
  src/app/js/formats/chart/asterPlotChart/AsterPlot.js
  src/app/js/formats/chart/hierarchy/Hierarchy.js
  src/app/js/formats/chart/hierarchy/utils.js
  src/app/js/formats/chart/parallel-coordinates/ParallelCoordinatesChart.js
  src/app/js/formats/chart/streamgraph/Streamgraph.js
  src/app/js/formats/chart/streamgraph/utils.js
  src/app/js/formats/checkPredicate.js
  src/app/js/formats/lodex/field/LodexFieldView.js
  src/app/js/formats/other/istexRefbibs/IstexRefbibsView.js
  src/app/js/formats/other/istexRefbibs/fetchIstexRefbibsData.js
  src/app/js/formats/other/istexSummary/FetchFold.js
  src/app/js/formats/text/code/CodeView.js
  src/app/js/formats/url/link-image/LinkImageAdmin.js
  src/app/js/formats/utils/components/default-format/DefaultAdmin.js
  src/app/js/formats/vega-lite/VegaLiteAdmin.js
  src/app/js/formats/vega-lite/component/bar-chart/BarChartAdmin.js
  src/app/js/formats/vega-lite/component/bubble-plot/BubblePlotAdmin.js
  src/app/js/formats/vega-lite/component/cartography/CartographyAdmin.js
  src/app/js/formats/vega-lite/component/heatmap/HeatMapAdmin.js
  src/app/js/formats/vega-lite/component/pie-chart/PieChartAdmin.js
  src/app/js/formats/vega/component/flow-map/FlowMapAdmin.js
  src/app/js/formats/vega/component/radar-chart/RadarChartAdmin.js
  src/app/js/lib/components/FormAutoCompleteField.js
  src/app/js/lib/composeRenderProps.js
  src/app/js/public/ScrollToTop.js
  src/app/js/public/resource/Detail.js
  src/app/js/public/resource/Resource.js
  src/common/getLocale.js
  src/test-utils.js
Labels: 👷‍♂️ Ready For Review

#2304 Upgrade mongodb driver
  .gitignore
  Makefile
  docker-compose.dev.yml
  docker-compose.spec.yml
  docker-compose.yml
  jest-mongodb-config.js
  jest.config.js
  package-lock.json
  package.json
  packages/ezsLodex/package.json
  packages/ezsLodex/src/reduceQuery.js
  packages/ezsLodex/test/mongoQueries.spec.js
  src/api/controller/api/field.js
  src/api/controller/api/publish.spec.js
  src/api/controller/api/publishFacets.js
  src/api/controller/api/publishFacets.spec.js
  src/api/controller/api/publishedDataset.js
  src/api/controller/testController.js
  src/api/models/configTenant.js
  src/api/models/dataset.js
  src/api/models/enrichment.js
  src/api/models/field.js
  src/api/models/field.spec.js
  src/api/models/hiddenResource.js
  src/api/models/precomputed.js
  src/api/models/publishedCharacteristic.js
  src/api/models/publishedDataset.js
  src/api/models/publishedDataset.spec.js
  src/api/models/publishedFacet.js
  src/api/models/publishedFacet.spec.js
  src/api/models/subresource.js
  src/api/models/tenant.js
  src/api/models/utils.js
  src/api/services/clearPublished.js
  src/api/services/enrichment/enrichment.js
  src/api/services/import.spec.js
  src/api/services/repositoryMiddleware.spec.js
  src/api/services/restoreModel.js
  src/api/services/restoreModel.spec.js
  src/api/services/restoreModel.testdata.tar
  src/api/services/saveParsedStream.js
  src/api/services/saveParsedStream.spec.js
  src/api/services/updateFacetValue.js
  src/api/services/updateFacetValue.spec.js
  src/common/tests/fixtures.js
Labels: 👷‍♂️ Work In Progress, 👷‍♂️ Do Not Merge

#2353 Replace react-connected-router by redux-first-history
  .travis.yml
  package-lock.json
  package.json
  src/api/controller/front.js
  src/app/js/admin/import/sagas.js
  src/app/js/admin/import/sagas.spec.js
  src/app/js/admin/index.js
  src/app/js/admin/navigation/sagas.js
  src/app/js/admin/reducers.js
  src/app/js/configureStore.js
  src/app/js/configureStoreServer.js
  src/app/js/fields/sagas/addField.js
  src/app/js/fields/sagas/removeField.js
  src/app/js/fields/sagas/saveField.js
  src/app/js/fields/wizard/index.js
  src/app/js/lib/sagas/fetchSaga.js
  src/app/js/lib/sagas/fetchSaga.spec.js
  src/app/js/public/Home.js
  src/app/js/public/Routes.js
  src/app/js/public/index.js
  src/app/js/public/reducers.js
  src/app/js/public/resource/sagas/loadResource.spec.js
  src/app/js/user/sagas.js
  src/app/js/user/sagas.spec.js
  src/test-utils.js
Labels: 👷‍♂️ Ready For Review

#2317 use the latest version of esz/basics
  package-lock.json
  package.json
Labels: 👷‍♂️ Ready For Review

#2366 Fix(enrichment): Add missing documentation link for SELECT operation
  packages/transformers/src/operations/SELECT.js
Labels: 👷‍♂️ Ready For Review

#2371 14.0.76
  Makefile
  package-lock.json
  package.json
Labels: 👷‍♂️ Ready For Review

#2367 Upgrade react redux
  package-lock.json
  package.json
  src/app/js/admin/preview/publication/sagas.js
  src/app/js/admin/preview/publication/sagas.spec.js
  src/app/js/admin/progress/sagas.js
  src/app/js/configureStoreServer.js
  src/app/js/fetch/sagas.js
  src/app/js/fetch/sagas.spec.js
  src/app/js/lib/sagas/updateReduxFormArray.js
Labels: 👷‍♂️ Ready For Review

#2378 Revert "Merge pull request #2278 from Inist-CNRS/2145-fix-network-chart"
  src/app/js/formats/chart/network/NetworkView.js
Labels: 👷‍♂️ Ready For Review

#2375 Feat(annotation): Add backend services to support annotations
  Makefile
  package-lock.json
  package.json
  src/api/controller/api/annotation.js
  src/api/controller/api/annotation.spec.js
  src/api/controller/api/annotation.validator.js
  src/api/controller/api/annotation.validator.spec.js
  src/api/controller/api/index.js
  src/api/controller/testController.js
  src/api/models/annotation.js
  src/api/models/annotation.spec.js
  src/api/services/repositoryMiddleware.js
  src/api/services/repositoryMiddleware.spec.js
  src/common/tests/fixtures.js
Labels: 👷‍♂️ Ready For Review

#2377 2145: refactor network format to use react-force-graph
  package-lock.json
  package.json
  src/app/js/formats/chart/network/NetworkView.js
Labels: 👷‍♂️ Ready For Review

#2382 Feat(annotation): Add frontend
  cypress/e2e/phase_4/annotation.cy.js
  cypress/support/annotation.js
  docker-compose.dev.yml
  docker-compose.spec.yml
  package-lock.json
  package.json
  src/api/controller/api/annotation.js
  src/api/controller/api/annotation.spec.js
  src/api/controller/front.js
  src/api/models/annotation.spec.js
  src/app/custom/translations.tsv
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/useCreateAnnotation.js
  src/app/js/annotation/useCreateAnnotation.spec.js
  src/app/js/annotation/useResourceUri.js
  src/app/js/annotation/useResourceUri.spec.js
  src/app/js/public/Property/index.js
  src/app/js/public/Routes.js
  src/app/js/public/index.js
  src/common/validator/annotation.validator.js
  src/common/validator/annotation.validator.spec.js
Labels: 👷‍♂️ Ready For Review

#2388 Feat(annotation): Administrators can disable annotations for some fileds
  cypress/e2e/phase_4/annotation.cy.js
  src/api/controller/api/publishFacets.js
  src/api/models/annotation.spec.js
  src/api/models/enrichment.js
  src/api/models/field.js
  src/api/models/field.spec.js
  src/api/models/precomputed.js
  src/api/models/subresource.js
  src/api/models/tenant.js
  src/api/services/updateFacetValue.js
  src/api/services/updateFacetValue.spec.js
  src/app/custom/translations.tsv
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/fields/FieldAnnotableInput.js
  src/app/js/fields/wizard/TabSemantics.js
  src/app/js/fields/wizard/index.js
Labels: 👷‍♂️ Ready For Review

#2396 Fix(dataset): Use aggregate instead of distinct to count unique fields to avoid oom
  src/api/models/countNotUnique.js
  src/api/models/countNotUnique.spec.js
Labels: 👷‍♂️ Ready For Review

#2408 Fix(annotation): Improve create annotation UX by using popover instead of modal
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
Labels: 👷‍♂️ Ready For Review

#2416 Chore: Merge v14 into v15
  Makefile
  cypress/e2e/phase_2/enrichment.cy.js
  package-lock.json
  package.json
  src/api/models/countNotUnique.js
  src/api/models/countNotUnique.spec.js
  src/app/custom/translations.tsv
  src/app/js/admin/enrichment/EnrichmentForm.js
Labels: 👷‍♂️ Ready For Review

#2418 Fix(fields): Improve delete field translations
  src/app/custom/translations.tsv
  src/app/js/admin/field/DeleteFieldsButton.js
Labels: 👷‍♂️ Ready For Review

#2415 Feat(annotation): Add contributor name support
  cypress/e2e/phase_4/annotation.cy.js
  cypress/support/annotation.js
  docker-compose.spec.yml
  src/api/controller/api/annotation.spec.js
  src/app/custom/translations.tsv
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/annotation/CreateAnnotationModal.js
  src/app/js/annotation/CreateAnnotationModal.spec.js
  src/app/js/annotation/fields/AuthorEmailField.js
  src/app/js/annotation/fields/AuthorNameField.js
  src/app/js/annotation/fields/CommentField.js
  src/common/validator/annotation.validator.js
  src/common/validator/annotation.validator.spec.js
Labels: 👷‍♂️ Ready For Review

#2419 fix findOneAndUpdate returnDocument option
  src/api/models/configTenant.js
  src/api/models/enrichment.js
  src/api/models/field.js
  src/api/models/field.spec.js
  src/api/models/precomputed.js
  src/api/models/publishedDataset.js
  src/api/models/publishedDataset.spec.js
  src/api/models/subresource.js
  src/api/models/tenant.js
  src/api/services/updateFacetValue.js
  src/api/services/updateFacetValue.spec.js
Labels: 👷‍♂️ Ready For Review

#2423 Fix(login): Users can now submit form with enter as expected
  src/app/js/user/LoginForm.js
Labels: 👷‍♂️ Ready For Review

#2427 2326 annotation field
  cypress/e2e/phase_4/annotation.cy.js
  src/api/controller/api/annotation.js
  src/api/controller/api/annotation.spec.js
  src/api/models/annotation.spec.js
  src/api/models/field.js
  src/api/models/field.spec.js
  src/app/custom/translations.tsv
  src/app/js/admin/annotations/AnnotationList.js
  src/app/js/admin/index.js
  src/app/js/annotation/CreateAnnotationButton.js
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/common/validator/annotation.validator.js
  src/common/validator/annotation.validator.spec.js
Labels: 👷‍♂️ Ready For Review

#2430 15.0.0
  Makefile
  package-lock.json
  package.json
Labels: 👷‍♂️ Ready For Review

#2431 2422: have truncate work with any value type
  packages/transformers/src/operations/TRUNCATE.js
  packages/transformers/src/operations/TRUNCATE.spec.js
Labels: 👷‍♂️ Ready For Review

#2433 Fix(fields): Automatically select field icons when editing a field
  .github/workflows/lodex-ci.yml
  cypress/e2e/phase_1/admin_display.cy.js
  cypress/support/fields.js
  src/app/js/fields/FieldToggleInternalScope.js
Labels: 👷‍♂️ Ready For Review

#2340 feat(theme lodex semantisation): reactive i pour la sémantisation
  src/app/custom/themes/istex/Readme.md
  src/app/custom/themes/istex/css/istex-internalclass.css
  src/app/custom/themes/istex/css/istex.css
  src/app/custom/themes/istex/lodex-theme.json
Labels: 👷‍♂️ Ready For Review

#2435 2328 annotation page
  cypress/e2e/phase_4/annotation.cy.js
  src/api/controller/api/annotation.js
  src/api/controller/api/annotation.spec.js
  src/api/models/annotation.js
  src/api/models/annotation.spec.js
  src/api/models/field.js
  src/app/custom/translations.tsv
  src/app/js/admin/annotations/AnnotationItem.js
  src/app/js/admin/annotations/AnnotationItem.spec.js
  src/app/js/admin/annotations/AnnotationList.js
  src/app/js/admin/annotations/useGetAnnotation.js
  src/app/js/admin/index.js
Labels: 👷‍♂️ Ready For Review

#2443 2440: fix name conflict with deleteOne
  src/api/controller/api/dataset.js
  src/api/models/dataset.js
Labels: 👷‍♂️ Ready For Review

#2444 2441 annotation session expiration
  src/app/js/admin/Appbar/AppBar.js
  src/app/js/admin/annotations/AnnotationItem.js
  src/app/js/admin/annotations/useGetAnnotation.js
  src/app/js/admin/annotations/useGetAnnotations.js
Labels: 👷‍♂️ Ready For Review

#2445 2324 fix multiple bugs
  cypress/support/annotation.js
  src/app/custom/translations.tsv
  src/app/js/annotation/CreateAnnotationModal.js
Labels: 👷‍♂️ Ready For Review

#2446 2326 fix typo / stay logged in accross tab
  src/app/custom/translations.tsv
  src/app/js/admin/api/tools.js
  src/app/js/annotation/CreateAnnotationButton.spec.js
  src/app/js/annotation/useCreateAnnotation.spec.js
  src/app/js/configureStore.js
Labels: 👷‍♂️ Ready For Review

#2447 2434: fix locale (instead of language) in i18n state
  src/app/js/i18n/index.js
  src/app/js/i18n/index.spec.js
  src/app/js/i18n/sagas/setLanguage.js
  src/app/js/i18n/sagas/setLanguage.spec.js
Labels: 👷‍♂️ Ready For Review

#2442 Feat(annotation): Add support for annotations on graphs and subresources
  cypress/e2e/phase_4/annotation.cy.js
  docker-compose.dev.yml
  src/api/controller/api/annotation.js
  src/api/controller/api/annotation.spec.js
  src/api/models/field.js
  src/api/models/field.spec.js
  src/app/custom/translations.tsv
  src/app/js/admin/annotations/ResourceTitleCell.js
  src/app/js/admin/annotations/ResourceTitleCell.spec.js
  src/app/js/admin/annotations/ResourceUriCell.js
  src/app/js/admin/annotations/ResourceUriCell.spec.js
  src/app/js/fields/wizard/TabSemantics.js
  src/app/js/fields/wizard/index.js
  src/app/js/public/graph/Graph.js
Labels: 👷‍♂️ Ready For Review

#2451 2331 add contributor in details page
  cypress/e2e/phase_4/annotation.cy.js
  src/app/custom/translations.tsv
  src/app/js/admin/annotations/AnnotationItem.js
  src/app/js/admin/annotations/AnnotationItem.spec.js
Labels: 👷‍♂️ Ready For Review

#2449 refactor(theme istex ICONO): add new pictures for graphLodex ICONO
  src/app/custom/themes/istex/ICONO/graphLodex-banniere-1920x460.jpg
  src/app/custom/themes/istex/ICONO/graphLodex-carre-1080x1080.jpg
  src/app/custom/themes/istex/ICONO/graphLodex-rectangle-1920x1080.jpg
Labels: 👷‍♂️ Ready For Review
